### ISSUE TITLE
Symbol _ETHREAD not in symbol table/symbol table not found

### ISSUE THREAD

**Issue by k-0-i** [volatilityfoundation/volatility3#1053]
**Describe the bug**
Unable to validate the plugin requirements: ['plugins.PsList.kernel.symbol_table_name']

**Context**
![image](https://github.com/volatilityfoundation/volatility3/assets/95953449/01e4a642-d5cf-4797-8dc2-270171a348b7)

**Install method**
```
 pip3 install volatility3-2.4.1-py3-none-any.whl
```
**env**
WSL 2

**Comment by ikelos** [comment]
Thanks very much for your issue, please could you report the issue with the output from running the plugin with `vol -vvv -f BI...` rather than just `vol -f BI...`?  Also, pasting in images makes it much more difficult for people to search for your issue if they're experiencing something similar, so in future please copy and paste the text of the issue you're experiencing...
