### ISSUE TITLE
Volatility3 not work - symbol and pdbconv problem

### ISSUE THREAD

**Issue by Giak1234** [volatilityfoundation/volatility3#1129]
Good morning,
I am trying to run volatility3 on my PC but I am getting problems as per the picture:
![1](https://github.com/volatilityfoundation/volatility3/assets/17331993/60a35f48-fe3f-4183-bbd0-e1e7b43272cb)
I am also trying to convert the file ntkrnlmp.pdb to JSON with pdbconv.py (*\volatility3-develop\volatility3\framework\symbols\windows\pdbconv. py) to add it to the \volatility3-develop\volatility3\symbols\windows\ntkrnlmp.pdb folder but running the command "python3 pdbconv.py -f krnlmp.pdb -o c:\pdb" I do not get the desired JSON. How can I generate the conversion? Could you please provide support?
Thank you in advance.
PS: I followed this guide "https://medium.com/insomniacs/volatility-3-downloading-windows-symbols-for-volatility-3-on-air-gapped-machines-7bf7a63521c7".

**Comment by Giak1234** [comment]
With REMnux is the same:
![2](https://github.com/volatilityfoundation/volatility3/assets/17331993/2e79430a-f140-442f-a3ba-d27e5e02fafe)

**Comment by ikelos** [comment]
So the two outputs you've listed suggest it's trying to download the PDB file, but failing.  Please could you post the output of trying to run `python3 pdbconv.py -f krnlmp.pdb -o c:\pdb` that you mentioned?  You'll need to have volatility3 installed on the system somewhere, if you're not using the `PYTHONPATH` environment variable to tell it where the local installation is.  It also looks like you provided a directory name, rather than the name of a file to the `-o` output parameter.  Please try something like `-o C:\pdb.json`, or just leave out the -o parameter and it should display to the screen.
