### ISSUE TITLE
Command missing in the Volatility Workbench

### ISSUE THREAD

**Issue by ShadowLoong** [volatilityfoundation/volatility3#1184]
Hi guys I am running volatility workbench on my Windows 10 PC and after the image was loaded the netscan/netstat commands are missing.

![no netscan](https://github.com/volatilityfoundation/volatility3/assets/25520544/22c8c5fb-0208-4a58-b832-d5a148f5574a)

**Context**
Volatility Version:  v3.0 Build 1007
Operating System:  Windows 10 22H2
Python Version:  
Suspected Operating System:  
Command:

**Comment by eve-mem** [comment]
It may be that the bundled version of volatility is out of date in that tool. 

Are you able to run the command using vol3 from python? If you still have errors it'll also let you save more logs to enable us to debug it. 

Equally you might have paid support from the company? That might be a route you could take? (I'd rather you did it here so we can fix it properly in the main tool)

**Comment by ShadowLoong** [comment]
Thank you. It is a free software so I didn't pay for the tool. Actually I thought it was the "official" GUI of Volatility3. Now it seems like to be an independent software so I will try to go with the CLI mode.

**Comment by ikelos** [comment]
This is not an official project of the Volatility Foundation, so support should be sought from the authors.  There isn't yet an official GUI for volatility, the closest we have is an example web GUI called Volumetric, which is also hosted under the Volatilityfoundation github.  Since this isn't an official project I'm going to close this ticket off...
