### ISSUE TITLE
pdbparse-to-json.py: KeyError: EnumIntegerString.new(8, 'T_HRESULT')

### ISSUE THREAD

**Issue by tklengyel** [volatilityfoundation/volatility3#120]
Running pdbparse-to-json.py results in the following error on a windows10 kernel pdb:

	PDB GUID: 80bdf49bd89d905be3a73d7f4226a90f1
	Kernel filename: ntkrnlmp.pdb

```
root@t1:/shared/volatility3# python3 development/pdbparse-to-json.py -f /shared/windows10/ntkrnlmp.pdb -o /tmp/test.json
INFO     __main__    : Parsing PDB...
INFO     __main__    : Reading usertypes...
INFO     __main__    : Reading enums...
INFO     __main__    : Reading symbols...
Traceback (most recent call last):
  File "development/pdbparse-to-json.py", line 353, in <module>
    json.dump(convertor.read_pdb(), f, indent = 2, sort_keys = True)
  File "development/pdbparse-to-json.py", line 138, in read_pdb
    "base_types": self.read_basetypes()
  File "development/pdbparse-to-json.py", line 311, in read_basetypes
    "kind": self.ctype_python_types.get(self.ctype[index], "int"),
KeyError: EnumIntegerString.new(8, 'T_HRESULT')

**Comment by ikelos** [comment]
Thanks for reporting this, it should now be fixed in commit `acc74af` in master.

Please note, we do not recommend using this tool to create PDB files (specifically, I believe it may not produce accurate array count values).  The recommended route is to use `pdbconv.py`, however I realize you've filed a different issue about that, so I understand your desire to turn to this tool.  We do not particularly intend to support it, it was more of a prototype/development tool whilst we were writing the official one (which is `pdbconv.py`).

I'm going to mark this as fixed, but please feel free to reopen if the problem doesn't go away for you...  5:)
