### ISSUE TITLE
Can the Volatility3 import external plugins?

### ISSUE THREAD

**Issue by MaxFuwin** [volatilityfoundation/volatility3#1248]

**Comment by ikelos** [comment]
Yes, volatility 3 is designed with a plugin system, and you can distribute plugins as python files (with data files if necessary) or as zip files (although I don't recall the exact internal directory structure needed for that, just that we added it).  The plugins must be under a directory identify which operating system they run against (windows, linux or mac) and you can specify the path to choose using `--plugin-dirs`.  If you have any difficulties, you might get quicker responses by asking on our slack channels at https://www.volatilityfoundation.org/slack rather than filing a bug report.  Bug reports should be for issues with the code not operating correctly, where possible...
