### ISSUE TITLE
Volatility 3 for Framework Designers (JSON Renderer as API)

### ISSUE THREAD

**Issue by mrratherford** [volatilityfoundation/volatility3#125]
In the Volatility 2 wiki there was a nice example on how to design a framwork around volatility that collects and processes plugin outputs based on the JSON renderer as API ([LINK](https://github.com/volatilityfoundation/volatility/wiki/Unified-Output#framework-designers)). 

I want to do the same with volatility3. To achive this i tried to go through the volatility3 cli classes and gather all relevant parts to build a working volatility environment. Unfortunately, the amount of reverse engineering to achive this goal ist huge. 

Is it planned to release a similar example as the one in the previous volatility version for the current version?

**Comment by ikelos** [comment]
Hiya, there were no express plans to do so, the [volatility3 documentation](https://volatility3.readthedocs.io/en/latest/) is now generated from the code and hopefully more extensive, meaning reverse engineering shouldn't be too arduous?

The CLI should be reasonably straight forward and [commented](https://github.com/volatilityfoundation/volatility3/blob/master/volatility/cli/__init__.py#L206) to show sections that are carried out by the UI and those carried out by the framework.

Please also consider looking at [Volumetric](https://github.com/volatilityfoundation/volumetric/), which is our toy example web interface, based on a simplistic example [web API](https://github.com/volatilityfoundation/volumetric/blob/master/volumetric/api.py).  In both instances, since the harness is written in python, we recommend leaving the results in [TreeGrid format](https://volatility3.readthedocs.io/en/latest/volatility.framework.renderers.html#volatility.framework.renderers.TreeGrid), however, we are developing a [JSON renderer](https://github.com/volatilityfoundation/volatility3/blob/json-renderer/volatility/cli/text_renderer.py#L282) to interface with the CLI using a different language if necessary (although, this work hasn't been merged into master yet).

Hopefully that gives you something to start with.  If you'd like to contribute some additional documentation, please consider writing an `rst` file we can add to the volatility3 documentation (see [`/doc/source`](https://github.com/volatilityfoundation/volatility3/tree/master/doc/source)), but even just letting us know what kind of questions you'd like answered would be useful.

Ideally questions like this are easier to handle in a more interactive medium, so please consider joining our slack channels to discuss this further?

I'll close this off in a day or two if I don't hear anything back, but feel free to reopen this if you can give us some direction and want to make sure similar documentation gets added...  5:)
