### ISSUE TITLE
Wrong proc mem extract from full RAM dump

### ISSUE THREAD

**Issue by hvprvtr** [volatilityfoundation/volatility3#1257]
Hello. Try to extract dump of lsass.exe from full RAM dump Windows 2016/2019 Server.
Full RAM dump maded by winpmem. 

`winpmem_mini_x64_rc2.exe phizmem.raw`

Search a PID i need:

`vol -f phizmem.raw windows.pslist`

Extract PIDs memory:

`vol -f phizmem.raw -o lsass windows.memmap.Memmap --pid 992 --dump`

No errors. I got dmp file with size 2.5Gb. It is a wrong size. 

Next step, i mount phizmem.raw by MemProcFS and got right dump - 50Mb size. It is a right size. 

Why volatile3 made broken dump? May be i do something wrong? 

**Context**
Volatility Version:  Volatility 3 Framework 2.10.0
Operating System:  Ubuntu 24.04
Python Version:  Python 3.12.3
Suspected Operating System:  Windows Server 2019/2016

**Comment by ikelos** [comment]
Volatility isn't involved in the acquisition of memory and unfortunately we can't help diagnose acquisition problems that easily.  Also, please note that if the machine was running between the two images, the state of memory will have changed and it's possible the first one experience memory smear (where references to earlier memory change as the recording happens).  Both tools may both be working correctly, but the memory capture not have captured cleanly because of the time it takes to image memory.

I'm afraid there isn't much more help we can provide.  Marking as closed, but if you feel there's more we can answer, feel free to reopen the ticket or ask for support on our [slack channel](https://www.volatilityfoundation.org/slack).
