### ISSUE TITLE
this page is strange

### ISSUE THREAD

**Issue by liberte97** [volatilityfoundation/volatility3#128]
vol.py -f <file path> windows.psscan --> this command result is error

![그림1](https://user-images.githubusercontent.com/35121677/68373649-a7c25e00-0186-11ea-9f8a-5c2dc725f2d1.png)

**Comment by ikelos** [comment]
Hiya,

Could you please verify that you're using the latest copy of volatility3 from git without any modifications?

This error message suggests that the psscan plugin is expecting to return a string for its first column, but the code in question should be expecting an integer (which a `Pointer` is), and that code [hasn't changed](https://github.com/volatilityfoundation/volatility3/blame/master/volatility/framework/plugins/windows/psscan.py#L67) in the repository in 8 months (so long before the public release).  It's therefore not clear why the plugin would be expecting a string to be returned?

**Comment by liberte97** [comment]
![image](https://user-images.githubusercontent.com/35121677/68376886-c0ce0d80-018c-11ea-96cd-ac549a6adcaf.png)

recent volatility is strange. 
In vol2 it comes out normally

**Comment by ikelos** [comment]
Volatility 3 is written in python3, which means that strings are now unicode by default.  This means that when invalid/corrupt data is displayed as a string it may display oddly (and include new lines or other special characters).  If you think this is problematic, please open a separate issue about it, and we'll be happy to make a decision on what the best behaviour for the tool would be...  5:)

If that wasn't what you meant by "normally", but in fact you get different results between volatility2 and volatility3 then please file a separate issue as well, and include both the vol2 and vol3 output against the same image.  Also, output to a file rather than images would be more useful for us to help diagnose the issue...  5:)

**Comment by liberte97** [comment]
This memory file is unicode?? 
not print iexplore.exe and rundll32.exe

![image](https://user-images.githubusercontent.com/35121677/68380806-e579b380-0193-11ea-8f69-c9968effc431.png)
vol2'result is normal
vol3'result translate txt --> this picture
vol3'result print --> 1hours ago picture

trouble process is iexplore.exe and rundll32.exe 
why this problem?
