### ISSUE TITLE
Implement poolscan checks for object validity and verify all constraints are accurate

### ISSUE THREAD

**Issue by liberte97** [volatilityfoundation/volatility3#131]
![image](https://user-images.githubusercontent.com/35121677/68384927-0cd47e80-019c-11ea-918a-ae1ad6ac1061.png)

vol2'result is normal
vol3'result translate txt --> this picture
vol3'result print --> closed ploblem 2hours ago picture

trouble process is iexplore.exe and rundll32.exe
why this problem?

**Comment by ikelos** [comment]
So volatility 2 often had a tendency to ignore errors that it ran into, whereas in volatility 3 we try to let the UI deal with errors as it sees fit.  This can become an issue when an error is raised whilst iterating a list.  Unfortunately, there's no easy way of figuring out if this is what's happened in volatility 2 (which is why we changed that), but we can add more error handling around Unicode errors there, so we can work on getting a fix in for that.  I'll keep this bug around until I've had chance to address it...

**Comment by ikelos** [comment]
The other image referenced is, I believe, the one from #128.

Looking into this further, this error should never happen, because when the filename is cast to a string all errors are replaced with a question mark (due to [`errors = 'replace'`](https://github.com/volatilityfoundation/volatility3/blob/master/volatility/framework/plugins/windows/psscan.py#L55)).

Please ensure the volatility code is not modified when reporting issues, we can't help with bugs in code we haven't written.  Pictures of the output don't show us everything that volatility produces, which makes it very difficult to determine what's actually going wrong.

If you are still experiencing this issue, please include the complete output (in a text file) of the successful run of volatility 2 and a similar run with volatility 3 without any modifications.  When running volatility 3 to provide the output to us, please use `vol.py -vvv` rather than just `vol.py`.  This will produce more output and allow us to see if anything unusual is happening.

**Comment by liberte97** [comment]
Could you give me the result of the test? 
https://drive.google.com/drive/folders/15g733nnEifMpB4OcMvmvB8_8uJZFwbF8?usp=sharing
Please CPO_PC.vmem 's psscan result

**Comment by ikelos** [comment]
Thanks for sending over the memory image!  The two entries you mentioned are present in memory, but they were terminated.  In volatility 2, there was a type check that was skipped during scanning to allow terminated processes to be found.  In volatility 3, we haven't implemented this, so the type checking is very strict and is ruling these entries out because they were previously terminated.

I've moved this over to @iMHLv2 since he'll know better how to implement this than I do.  I've tried adding in something to bypass the check but it then returns lots and lots of rubbish.  I couldn't easily see what other checks happened in vol2 but I suspect it's some of the `CheckPoolType`/`CheckPoolIndex`/`CheckPoolSize` checks that were done...  5:)

**Comment by ikelos** [comment]
Ok, so as best I can tell, the extra rubbish is due to us looking for both the `Pro\xe3` and also the `Proc` tag.  There's also a little extra junk from the `Pro\xe3` tag because of vol2 calling `is_valid` which is bespoke per executive object, which I don't think we have in vol3 (yet), but all the CheckPool* checks seem to be in place (although the index check has been omitted, and was broken in the code).

**Comment by ikelos** [comment]
Lastly, the `page_type`s could do checking, they seem to allow all types at the moment?

**Comment by liberte97** [comment]
The error hasn't been corrected yet, has it?
Then I'll wait for the error to be corrected.

**Comment by ikelos** [comment]
No, not yet I'm afraid, but we've got a clearer idea of exactly what's different...

**Comment by ikelos** [comment]
Ok, #132 has been merged now which should have helped somewhat.  Things we still need to figure out about:

* Are there other checks or index constraints that still need to be added?
* Investigate whether the `Proc` tag can be tweaked to reduce the junk it produces

It would be helpful if you could give this a go and let us know whether the results are at least better...  5:)
