### ISSUE TITLE
Reports about failed windows images are on the increase

### ISSUE THREAD

**Issue by ikelos** [volatilityfoundation/volatility3#1374]
We've been getting more reports of failed windows images, all with a similar MO, basically several potential kernel's found, but all cause a page fault.  Then even the slow scan fails.  That means either the WindowsIntel layer isn't mapping properly, or the kernel's living in compressed memory (unlikely, since what would put it there, since Windows doesn't load itself?) or when we trace back from the PDB signature we run across memory that isn't mapped in some way. 

```
Potential kernel_virtual_offset caused a page fault: 0xf80100400000
```

In any cirumstance, it would be good to get a sample and investigate this to see if we can solve it.

**Comment by the-rectifier** [comment]
I did a quick `git bisect` from a known good commit (https://github.com/volatilityfoundation/volatility3/commit/af7a420cdc14689ee6d2ff72d5ac8eefad9e833d) and the first bad commit was https://github.com/volatilityfoundation/volatility3/commit/73d4f2fc88e15ac038f962cb5f5b11acf7855091 which is a bit strange since it's linux changes.

In any case, here is a sample of a failing Windows 10 snapshot: https://next.alpha-carinae.xyz/s/HC3jerJ7brrt5s5 taken using `VBoxManage debugvm [VM] dumpvmcore --filename` and the relevant debug log
[burner.elf.log](https://github.com/user-attachments/files/17997966/burner.elf.log)

**Comment by ikelos** [comment]
Hmmm, thanks very much for bisecting that!  @gcmoreira was mostly intending to affecting linux but threw in a couple of lines to tidy up the maths for the intel layer.  Unfortunately that removed masking off the top of a 64-bit address to just the available physical page address.  This lead to issues that were swallowed by the scanner which skips errors as unmapped pages.  That lead to some windows images being missed when scanned.

That's now been fixed as of 73d4f2f.

Thanks very much for locating an image and bisecting it to find the problematic commit!  Great work!  5:D

**Comment by gcmoreira** [comment]
Oops, good catch! Thanks for fixing it so quickly! Sorry about that

**Comment by atcuno** [comment]
@the-rectifier would you be okay with us saving your memory sample and eventually incorporating it into an automated testing suite? We are designing a regression testing flow that will run against PRs to avoid issues like this and your sample would be perfect since it triggered a deep layer bug. Thanks.

**Comment by the-rectifier** [comment]
there is nothing special with this sample. I just created the VM because a (private) snapshot I was testing wasn't working, so feel free to use it!
