### ISSUE TITLE
Read the Docs volatility3.framework.constants

### ISSUE THREAD

**Issue by j-t-1** [volatilityfoundation/volatility3#1409]
[Volatility 3 Constants](https://volatility3.readthedocs.io/en/latest/volatility3.framework.constants.html)

1. `CACHE_PATH = '/home/docs/.cache/volatility3'` is this still correct?
2. I would like to reorder `LOGLEVEL_INFO = 10`and `LOGLEVEL_DEBUG =20`, how to do this?
3. Where is `bit_count()` defined?

**Comment by ikelos** [comment]
1. Not strictly, it *should* use the XDG specification for where to store cached files.  I think on windows it puts it under `%USERPROFILE%/Temp` but I'm not certain off the top of my head.

2. These shouldn't change, the unix/python logging system mimics syslog, where you set a log level and everything *higher* than that gets output.  Setting `DEBUG` above `INFO`, means that if you ask for `INFO`, you'd get both `DEBUG` and `INFO`.  The numbers are very specifically chosen to have reasonable values.  `INFO` is 20 by default and `DEBUG` is 10 (to match `logging.INFO` and `logging.DEBUG`).  Setting a log level of 0 means you get ALL log messages.  See [here](https://docs.python.org/3/library/logging.html#levels) for more information.

3. `bit_count` is a built-in method of python integers, documented [here](https://docs.python.org/3/library/stdtypes.html#int.bit_count).  Since `Parallelism` inherits from `enum.IntEnum` it actually represents a standard `integer` most of the time and therefore imported the documentation for standard integers as part of that.

**Comment by j-t-1** [comment]
Understood, thanks for this.

1. I could change to `$HOME/.cache` as a like for like replacement.
2. The order they are presented on the Read the Docs page change could be swapped still, so the `-v` flag increases by one as you read downwards?
3. Probably should have known this!

**Comment by ikelos** [comment]
1.  Yeah, I'd be ok with that although it's not strictly accurate but a closer approximation.

2. I think the constants are alphabetical but yeah, the numbers they relate to actually become more verbose as they approach 0.  Happy for you to reorder them if you think that'll increase readbility?  The topic does require understanding of the `logging` module though, so it might be more useful to include a comment around that than reordering them?  The number they relate to really isn't important, it's the name which should match up with the number of vs you need (after the first two)...

3. Well, I had to go scrobbling to figure it out.  That's why we have reference books, to store all the stuff it's not really important whether we know or not!  5:D

**Comment by j-t-1** [comment]
Will have a read of the `logging` module and do 1. and 2. I may be understanding this wrongly, but this web page is auto generated somehow, or is there a source file that corresponds to that page?

**Comment by ikelos** [comment]
Err, that page is autogenerated, which would explain why it says `/home/docs` that'll be the home directory of the container user that builds the documentation...  5:S  Might be more trouble than it's worth to fix that?  It does read the comments just beneath it, but changing that default value could be tricky to fix...

**Comment by j-t-1** [comment]
Will get more of a handle of the process, and may or may not update this. Thanks, understand this much better now.
