### ISSUE TITLE
Redirecting output to txt file is messed up

### ISSUE THREAD

**Issue by hakija** [volatilityfoundation/volatility3#142]
When redirecting the output to a txt files via ">" or ">>" the output file is not formatted properly...please see attach. Any fix for this?! As far as i see it, there is a tab missing if length is below 8 chars, but I see other errors as well...
[pslist.txt](https://github.com/volatilityfoundation/volatility3/files/3860822/pslist.txt)

**Comment by ikelos** [comment]
Yep, that's because you're using the quick renderer, which is designed to give immediate results on the command line for investigators to see how the plugin is working.  It's therefore also the default output mode.

If you're going to be outputting it to a file and would like the output suitably formatted, please try `vol.py -r pretty` rather than `vol.py`.  It changes the renderer to the pretty renderer, which will produce properly aligned tables and output.  It can do this because it generates all lines and then commences output, knowing the exact widths to have to make the various columns, rather than the quick renderer which outputs a line as soon as it is produced (but therefore cannot know how wide a column may need to be).

I hope this answers your question, I'll be closing this, but if you feel your issue hasn't been addressed, do feel free to reopen it.  5:)

**Comment by hakija** [comment]
That is fantastic, thanks!!!!
