### ISSUE TITLE
procdump

### ISSUE THREAD

**Issue by liberte97** [volatilityfoundation/volatility3#160]
It differs when you view the hash value of the same file. Is the procdump of ver 2 and 3 different?

in this page's https://www.jaiminton.com/Defcon/DFIR-2019/#15-8675309---35-points problem 08

volatility3 print : pid.[pid].dmp
volatility2 print : ex~.exe

**Comment by ikelos** [comment]
The plugin has been rewritten and so may produce slightly different output, but I've assigned the plugin author to see if something's up with the code or not...  5:)

**Comment by doomedraven** [comment]
yes dumped files are diff in v2 and v3 i already had to deal with that

**Comment by ikelos** [comment]
A little more information, this is because the volatility3 `procdump` plugin currently outputs files as if they had been dumped by volatility2 with `--memory` (ie, it's dumping the memory image, not the reconstructed PE file).  I'm not sure what the game plan is for adding support for dumping as the on-disk format rather than the memory format, but I imagine we'll be adding it at some point...

**Comment by doomedraven** [comment]
thanks for the headups

**Comment by ikelos** [comment]
Hiya, we're not sure there's a significant requirement for wanting the on-disk format of files rather than the `--memory` output from volatility 2, so I'm likely to close this issue.  If you do feel it's important, please reopen it, but it's unlikely to get much traction in the next few months as we divert our energies towards newer features and polishing up the core framework...

**Comment by railabouni** [comment]
hello,
I cannot find the procdump plugin anymore, was it removed? why?

**Comment by ikelos** [comment]
It wasn't removed, the `*dump` plugins have been converted into `--dump` flags for various plugins.  I think `procdump` has been merged into `pslist` so `pslist --dump` should provide the same functionality.

**Comment by railabouni** [comment]
ohh I see! thank you so much!
