### ISSUE TITLE
VadDump AttributeError: ObjectTemplate object has no attribute size

### ISSUE THREAD

**Issue by tacintel** [volatilityfoundation/volatility3#177]
**Describe the bug**
Running windows.vaddump.VadDump I receive a final error of  AttributeError: ObjectTemplate object has no attribute size.  Also seeing approximately 9 errors similar to this
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK

**Context**
Volatility Version:  3 Framework 1.0.0-beta.1
Operating System:  Win 10 Pro
Python Version:  Tried 3.8.1 and 3.7.6
Suspected Operating System:  Tried Win10.dmp and Win8.vmem
Command:  python vol.py -vvvvv -f "C:\mem\w8.vmem" windows.vaddump.VadDump
also tried python vol.py -vvvvv -f "C:\mem\w8.vmem" windows.vaddump.VadDump --pid 204 
**To Reproduce**

1. Use command '...'
2. See error

**Expected behavior**
expected a dump of Vad for each process

**Screenshots**
![2020-01-15 18_33_09-Command Prompt](https://user-images.githubusercontent.com/3131489/72483131-95d3eb80-37c5-11ea-9a21-a5062561d3d8.jpg)

**Additional information**
Add any other information about the problem here.

**Comment by sn0w0tter** [comment]
I have same issue on macOS Mojave 10.14.6 with python 3.7.5.
Beside ```windows.vaddump.VadDump``` I found ```windows.malfind.Malfind``` throwing same error.

**Comment by ikelos** [comment]
Thanks for the report, we recently added the size property for all objects.  Unfortunately the review process wasn't as thorough as hoped, so certain types didn't end up with the right code.  This was the `bytes` type (for both vaddump and malfind), but this should now have been resolved as of 572313cc34633f54c089a6fb0b464475d7b7a7fb.  Do please report if you encounter any other similar problems, and thanks again both for the quick reports!  5:)

**Comment by ikelos** [comment]
I'll close this off, but if you still encounter the error, feel free to reopen it.  5:)

**Comment by ikelos** [comment]
@tacintel the debugging references about unresolved symbols are unfortunately expected.  It's when a particular type in the tree (the `QuotaBlock` field of an `_EPROCESS` in this case, which contains a pointer to an `_EPROCESS_QUOTA_BLOCK`) exists without the type being defined in the pdb.  This happens when Microsoft releases incomplete PDBs (it's not clear why they would, but they do, perhaps for security reasons?).  In those instances we spot that there's a reference to it, but that we don't have it (and we log it in the debugging information).  They're not often required, but if someone wrote a plugin that needed one of these, they'd need to be written by hand.  I hope that explains the debugging message?
