### ISSUE TITLE
Vaddump output to use ImageFileName instead of PID

### ISSUE THREAD

**Issue by tacintel** [volatilityfoundation/volatility3#178]
**Is your feature request related to a problem? Please describe.**
On a memory sample I like to run Vaddump on all processes.  I then place the exported .dmp files into my favorite forensic tool and I search for dozens of keywords.  When I get hits  I have constantly reverse the PIDs to the ImageFileNames so I can decide if I'm looking at malicious code or something in a process that is probably benign, like an AV process

**Describe the solution you'd like**
Vaddump output to use ImageFileName instead of PID.  So right now I get:
pid.4176.vad.0x7fffff2a000-0x7fffff2bfff.dmp

I would like the following:
MsMpEng.exe.vad.0x7fffff2a000-0x7fffff2bfff.dmp

or even 
MsMpEng.exe.pid.4176.vad.0x7fffff2a000-0x7fffff2bfff.dmp

**Describe alternatives you've considered**

**Additional information**
I believe Vol2 exports VAD with the  ImageFileName

**Comment by iMHLv2** [comment]
@tacintel We are looking into this. Traditionally, we've tried to avoid using strings from the memory sample to produce file paths on an analyst's machine, since the strings may be untrusted. Our plan is to start using the strings as you've requested, but after we properly sanitize the strings to remove invalid characters and directory traversal attempts, etc.

**Comment by ikelos** [comment]
So the upshot of this is we can probably reasonably easily determine whether a path is valid or not (rely on python and verify that  `dirname(normpath(abspath(path)))` matches the directory we expect to be writing into), but the downside is what to do if it's not?  There is a "slugify" function that django uses, which we would either need to depend on as a dependency or reimplement ourselves, neither of which are attractive options because even that is a best efforts attempt to avoid vulnerabilities.  We could go down the whitelisting route, which I'd feel happier with, but that would likely rule out most unicode characters/unusual character sets (and would have to be common across operating systems, so would be the most restrictive subset of acceptable characters).  5:S

I'm not sure what would be more useful in this instance:
* not including untrusted data (so no filename-data in the output filename, ie what we currently have)
* checking the data on file writes and if it fails returning a filename without any useful data in it
* having each function that writes files doing its own check and try to return as much data as safely possible
* whitelisting and therefore only likely working properly for latin-1/windows-1251 characters.

@iMHLv2 Any thoughts?

**Comment by ikelos** [comment]
Given the need to support unicode, this would be extremely difficult to implement, so we're not going to trust (potentially) random data taken from an image that isn't in a format we can ensure is safe (such as the pid).  Unless someone can come up with a good way to ensure we can use the filename (perhaps as hex bytes, but that won't be all that helpful) I'm closing this off.  Feel free to reopen if you have a suggestion or a strong opinion...
