### ISSUE TITLE
Windows DTB is misdetected as 32bit rather than 64bit

### ISSUE THREAD

**Issue by btaubmann** [volatilityfoundation/volatility3#193]
**Describe the bug**
Volatility fails to work on a windows image

**Context**
Volatility Version:  3
Operating System:  ubuntu 16.04
Python Version:  3.5
Suspected Operating System:  windows
Command:  windows.pslist

Unsatisfied requirement plugins.PsList.primary: Memory layer for the kernel
Unsatisfied requirement plugins.PsList.nt_symbols: Windows kernel symbols
A symbol table requirement was not fulfilled.  Please verify that:
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner
A translation layer requirement was not fulfilled.  Please verify that:
	A file was provided to create this layer (by -f, --single-location or by config)
	The file exists and is readable
	The necessary symbols are present and identified by volatility

**To Reproduce**

I created a travis script to reproduce the problem https://github.com/bentau/volchecker
The travis log can be found here: https://travis-ci.org/bentau/volchecker

**Comment by ikelos** [comment]
Thanks for the report, this looks very similar to #192 which quite correctly came to the conclusion that unfortunately we don't yet support the AFF4 file format.  If you can convert it to a raw image (I believe volatility2 has support in the contrib area) that should then be possible to process with volatility 3.  I'm not sure when/whether AFF4 is on the timeline at least for the first official release, but we'll keep this open so we know it's been requested...  5:)

**Comment by btaubmann** [comment]
it is not aff4 anymore. i converted the image to raw before the analysis

**Comment by ikelos** [comment]
Ah, I missed that sorry!  5:S  Cool, I'll take a look when I get a chance (this week is quite busy, but I'll see what I can do towards the end of the week)... 5:)

**Comment by ikelos** [comment]
Having dug a little more into this, can you please confirm that the AFF4 file is successfully converted into a raw file?  Volatility2 doesn't natively support AFF4, it requires an add on to be installed from the community repository (and that comes with a number of dependencies that I haven't yet been able to successfully install).  Volatility2 doesn't provide an error when running imagecopy, but since it can't determine any layers below the first, I believe it's just copying the file?

You can verify this by running md5sum against both the original and the created raw file, and if they're the same then no conversion's happened.  If you've managed to get the dependencies properly installed and it converted, and volatility 3 still doesn't run against it, then perhaps you can provide a copy of the converted file for us to run tests against?  At the moment, getting it convert from the aff4 format seems to be the issue...

**Comment by bentau** [comment]
You were right, volatility did not convert it correctly. I fixed it by converting it manually using rekall.
Now I use my converted image which is stored here https://gandra.fim.uni-passau.de/~tux/win10.zip

Volatility2 works on this images and prints the pslist
However volatility3 still does not work.

The log is here: https://travis-ci.org/bentau/volchecker/builds/656190681

**Comment by ikelos** [comment]
Hmmm, so this misdetects the DTB as being at `0x730000` because of the self-referential offset for 32-bit systems.  It's actually a 64-bit system and the correct DTB is `0x1aa000`.

The resolution for this is likely to be to change the order of the tests (since 64-bit is likely more precise and more common these days), but we'll need to discuss it before we make the change.  In the interim, you can create a file that tells volatility it is a 64-bit system and the correct DTB to use, so in a `<json_file>` file put:
```
{
  "primary.class": "volatility.framework.layers.intel.WindowsIntel32e",
  "primary.page_map_offset": 1744896
}
```
Then to run volatility use:
```
python vol.py --config <json_file> -f <image_file> <plugin_name>
```
I'll leave this open until we get it resolved.  I'll change the title of the issue so we can see what the actual issue is, but if you'd like AFF4 support, please open another issue so we can track it separately...  5:)

**Comment by btaubmann** [comment]
Thanks with the config it works.

I don't need AFF4 support. I just wanted to play around with volatility3 and stumpled across this file from rekall
