### ISSUE TITLE
PStree issues 

### ISSUE THREAD

**Issue by SuperbSonik** [volatilityfoundation/volatility3#194]
**Describe the bug**
PStree doesn't work

**Context**
Volatility Version:  3
Operating System:  Windows 10x64
Python Version:  Python 3.8.2
Suspected Operating System:  Windows10x64

Currently I am using Volatility 3 to perform pstree command but it took super long time, and I force cancel the operation and it shown a list of errors as stated below:

![image](https://user-images.githubusercontent.com/61529488/75526009-e341aa80-5a4b-11ea-9be4-0ddf8d9e2712.png)

I would appreciate if anyone can give me some ideas, thank you all. 

Volatility 3 is really better than 2, I like the way it notify the user about the progress percentage and the progress is growing smoother. Thank you!

**Comment by ikelos** [comment]
Hmmmm, thanks.  Could you please rerun your testing using `vol.py -vvvvv` instead of just `vol.py`?  That should give us more information about what volatility thinks the memory image is.  Windows 10 scanning can take a really long time, but that usually during a `scan` plugin rather than just something like pslist/pstree...  Also, do other plugins run ok, or is it just pstree that causes problems?

**Comment by SuperbSonik** [comment]
Good morning, sorry for the late reply. These are the outputs I get:
![image](https://user-images.githubusercontent.com/61529488/75637947-8a009380-5c64-11ea-889c-fbd872ba0133.png)

![image](https://user-images.githubusercontent.com/61529488/75637958-9b49a000-5c64-11ea-8987-a35eeaef21d2.png)

![image](https://user-images.githubusercontent.com/61529488/75637966-a7356200-5c64-11ea-8afb-013274d98bee.png)

I haven't try the other plugins yet, will let you know if there is any issues

**Comment by ikelos** [comment]
Morning!  Thanks for that output, there doesn't look to be anything unusual with that?  It detects the DTB (and in about the place I'd expect it) and then it locates the kernel header and loads the appropriate symbols for it.  It's really not clear why it's taking so long to scan (particularly since it shouldn't be scanning, it's just going to an offset from the symbol table and traversing a list from there)...  5:S  If you could let us know how other plugins perform, that might help.  For the meantime I'll take the further information flag off, and have a ponder over possibilities...

**Comment by ikelos** [comment]
(As a side-note, cancelling things with Ctrl+C will always cause errors, since we don't catch the KeyboardException and it prints out the line it got to when it was cancelled).

**Comment by ikelos** [comment]
So actually, my best guess is we try to iterate the list, the image has a problem with it somewhere, and it never loops back around whilst we're waiting to stop it when it does, so it just carries on forever.  We'll probably need to put some depth limits or something in there...

**Comment by SuperbSonik** [comment]
Thanks for your reply, it really helps a lot.

**Comment by ikelos** [comment]
Hmmm, that all looks ok.  It's very hard to tell why it would be taking so long given that it found an intel layer and determined an appropriate pdb file to use for symbols?  With those it should be able to jump right the address of the process list and traverse it.  It's possible that the distance between the kernel header and the start of the kernel came out incorrectly, but we don't have that level of debugging information exposed...  5:S  Would you be able to make the image available so we can investigate it further?

It'd also be really helpful to find out whether any other plugins worked better with it or not...

**Comment by ikelos** [comment]
D'oh, I didn't refresh my page and forgot I'd already answered this, sorry!  5:S
