### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by tnazzaro** [volatilityfoundation/volatility3#211]
I have RHEL7 memory dump and profile created from a an instance running on s390x chipset. Volatility (py2 or py3 versions) does not detect it properly. I would like to create s390x support, but I do not know where to begin. I am not a programmer, per se, but do a bit of python scripting for smaller purposes. Is there anybody in the community who can point me in the right direction?

**Comment by ikelos** [comment]
Hiya, you'd need to figure out how the memory is laid out, and then develop a layer that can interpret a virtual memory address and turn it into a physical memory address, so that when a plugin asks for something in your layer, you know where it lives in a lower layer.  You might find [this documentation](https://volatility3.readthedocs.io/en/latest/volatility.framework.interfaces.layers.html#volatility.framework.interfaces.layers.TranslationLayerInterface.mapping) useful, it's the method you'd need to define in your layer that takes a virtual address (or a range of virtual addresses) and maps them into their location in the lower layer.  Unfortunately we haven't yet filled in [this part of the documentation](https://volatility3.readthedocs.io/en/latest/complex-plugin.html#writing-new-translation-layers) yet...

The most common architecture we deal with is the [intel x86/x64](https://github.com/volatilityfoundation/volatility3/blob/master/volatility/framework/layers/intel.py) architecture.  At the moment, those are about the only ones we support, although we're looking at adding arm/arm64 at some point (see #161).  If you don't specifically have a bug but are more interested in help to develop a new layer, you might want to join the [volatility slack server](https://www.volatilityfoundation.org/slack) and then join the #vol3-dev channel.  You're more likely to get interactive help there...  5:)
