### ISSUE TITLE
Linux - Cannot get an object from a symbol

### ISSUE THREAD

**Issue by gcmoreira** [volatilityfoundation/volatility3#279]
**Describe the bug**
object_from_symbol() fails when I tried to get "nf_hooks".
```
vmlinux.object_from_symbol(symbol_name = 'nf_hooks')
volatility.framework.exceptions.SymbolError: Template contains no information about its structure: vmlinux1!list_head
```
However, I can get the individual symbol & type

```
context.symbol_space.get_symbol("vmlinux1!nf_hooks")
<volatility.framework.interfaces.symbols.SymbolInterface object at 0x7f0fcb9e7fa0>
```

```
context.symbol_space.get_type("vmlinux1!list_head")
<volatility.framework.objects.templates.ObjectTemplate object at 0x7f0fcbbf6f70>
```

**Context**
Volatility Version:  1.1.0-beta.1 (master)
Operating System:  Ubuntu 20.04 LTS
Python Version:  3.8.2
Suspected Operating System:  kernel 3.13.0-117 / Ubuntu 12.04 

**To Reproduce**

1. Use command '...'
```
vmlinux.object_from_symbol(symbol_name = 'nf_hooks')
```

2. See error
```volatility.framework.exceptions.SymbolError: Template contains no information about its structure: vmlinux1!list_head```

**Expected behavior**
get the nf_hook obj

**ISF**

[linux.zip](https://github.com/volatilityfoundation/volatility3/files/5022492/linux.zip)

**Additional information**
Due to this distro version is too old, it's not anymore in ddebs.ubuntu.com and I couldn't find the original ubuntu dbgsym package anywhere. So, I ended up creating the dbgsym package from the kernel sources as it is explained in " [How do I build a debuginfo kernel if one isn't available?](https://wiki.ubuntu.com/Kernel/Systemtap)"

**Comment by ikelos** [comment]
Hiya, so I was right, this is pretty deep inside our machinery, but I've produced a patch that now suitably takes care of `ReferenceTemplates` in symbol types.  Something this has highlighted which I think I knew subconciously but never clearly expressed, is that getting symbols or types should *always* happen through the context symbol space (or a module, which does it this way) rather than explicitly getting a symbol table and then asking things of it.  `ReferenceTemplate`s may refer to a different symbol table, and rather than having symbol tables be aware of their siblings, we instead mandate that all lookups should happen through the `symbol_space` which is aware of all loaded tables. 

That's not what was going on here (you were using a module, which asks the symbol_space, and is why the patch works in this case), more just a note for myself and to explain a bit about the split.  5:)

Anyway, pull request #280 should resolve your issue, it should get merged into master shortly, but if you could test it for us that would help make sure I've not missed something...  5:)

**Comment by gcmoreira** [comment]
@ikelos That fix worked, thank you very much!

**Comment by ikelos** [comment]
Glad it worked, I'm going to keep the bug open until the patch lands in case someone else runs into it, but thanks for testing it!  5:)
