### ISSUE TITLE
Mention --pid within the vol.py help text

### ISSUE THREAD

**Issue by Id3aFly** [volatilityfoundation/volatility3#281]
**Describe the bug**
When you read the help text of volatility (vol.py -h) there is no information how to enable the pid filter `--pid <number>`.
In fact this information is only visible, when you read the plugin specific helpctexts, which can be shown with `vol.py <pluginname> --help`.
As discussed in slack, it would be good to mention this `vol.py <pluginname> --help` command not only right behind the  "-h"
flag description in the main vol.py help, but additionally further down in the plugin-section, right at the start before the description of all plugins.
By doing this, one could also point out, that plugin specific parameters need to be listed after specifying the plugin.

**Context**
Volatility Version:  Volatility 3 Framework 1.1.0-beta.1
Operating System:  Ubuntu
Python Version:  3.x

**To Reproduce**
Run vol.py -h.

**Expected behavior**
The help text should inform a user better, how to show plugin specific help.

**Comment by ikelos** [comment]
As of `a80400c` we now mention plugin specific options twice to the help message (once on --help and once just below the plugins list).  If you think the text could be improved or moved elsewhere, please let us know (feel free to reopen this).  We'd like this to be as clear and usable as possible, but since we know how it's expected to work it's hard for us to figure out exactly where/what the text should be, so any help you can provide would be appreciated...  5:)
