### ISSUE TITLE
memdump should take `-p` as an alternative option

### ISSUE THREAD

**Issue by SuperStormer** [volatilityfoundation/volatility3#320]
**Is your feature request related to a problem? Please describe.**
Currently, memdump takes --pid as its only option. 

**Describe the solution you'd like**
It should also accept -p, matching volatility 2.

**Comment by ikelos** [comment]
Hi there,

Thanks for requesting that me match the previous version of volatility, however, volatility 3 has been designed as a library to support multiple user interfaces, almost all other forms of which short options wouldn't make much sense.  There's no good reason for a web page to know that it can ask people for a `pid` or for a `p`.  We'd therefore be adding the feature specifically to the library in order to support just the CLI, and we don't want to clutter the configuration mechanism for a specific form of UI.

That then leaves the user interface itself trying to supply short options for the parameters it knows about.  It may be possible to write an algorithm that takes the first letter of each option on a first-come first-serve basis, but then how should it choose a follow up letter (if we had `--pid` and `--print` options, for example, would one be `-p` and the other then `-r`?  What if we had `--pid`, `--print` and `--repeat`, would the third option be given `-e`?).

We realize that volatility 2 has been around for a while and people have expectations of similarity between the tools, but there were a number of design decisions made for volatility 2 that we've explicitly changed for volatility 3, and one of those is the mechanism of interface with the actual library itself (volatility 2 was more of a command line tool that people could access the internals of, whereas volatility 3 was designed from the start with separation between UI and library).  We hope you understand that rather than chaining ourselves to the way that volatility 2 worked, we'd prefer that our users understood that volatility 3 has changed and that some of the ways they interact with it will have to change as well.  We hope this doesn't cause too much inconvenience, but once muscle memory has worn off we think this means of providing options will be more capable and clearer than volatility 2's method of doing things, for all user interfaces.

As such we're not intending to support short options in the CLI, but we're happy for others to write an interface that does support it using the library mechanisms available in volatility 3...
