### ISSUE TITLE
Winpmem support

### ISSUE THREAD

**Issue by vivianezw** [volatilityfoundation/volatility3#353]
There is a 'working' Winpmem version again: https://github.com/Velocidex/WinPmem (yes, suitable for latest Win10.)
It's only testsigned at this moment and some design things might change. For further notes and details check the repo. 
(And please note the Rekall repo is deprecated now. ) 

I'm now trying to figure out what you (the "Volatility 3 people") might need in addition to the (raw) Windows image dump. I only vaguely know what kind of additional data/hints would be useful for you. (And I figured out the format might be a json file?) 

Proposal: if you want extra nice support from Winpmem, can you please make me some write down, a kind of wishlist? 
Such as: jsonfile? CR3? Kernelbase VA? What else? I will be trying my best, though no guarantees.

**Comment by ikelos** [comment]
Thanks very much, volatility 3 is designed to work with raw memory dumps, so that should be enough.  The CR3/dtb and kernel_virtual_offset are useful, but would require a specific config.json file to be passed with the memory image.  The symbols that the image uses are based on the pdb of the kernel, which is derived from Microsoft via the GUID and age of the pdb (which we can extract from memory).  As such, I'm not sure that you need to provide anything extract, and volatility is designed primarily to work in those environments, but if you wish to provide additional information then that's what we'd use.  You can see which offsets/values are most commonly used by running `vol.py --write-config -f <image> windows.pslist`.  If that results successfully you should be left with a `config.json` file that indicates how the image is loaded and which variables it identifies and stores.  Hope this helps, and feel free to ask for more information if you need it.  Otherwise we'll probably mark this as closed somewhere down the line...

**Comment by vivianezw** [comment]
Sounds like you don't need anything more then. It should be working then already in theory.
