### ISSUE TITLE
PyPI: Official release

### ISSUE THREAD

**Issue by Wenzel** [volatilityfoundation/volatility3#357]
**Is your feature request related to a problem? Please describe.**
I would like to add `volatility3` package in my project's `requirements.txt`

**Describe the solution you'd like**
An upload of `volatility3` package to PyPI

**Describe alternatives you've considered**
The alternative is to git clone the repo and pip install it, which is not automated and doesn't fit in my workflow.

So, how far are we from a PyPI release ?

If you want to automate the process via Github Actions, I did that a few weeks ago on [checksec.py](https://github.com/Wenzel/checksec.py):
https://github.com/Wenzel/checksec.py/blob/master/.github/workflows/ci.yml#L152

The CI will publish in PyPI only if the tag is set to `v*` (`v0.2.4` for example)

What's your opinion ?

Thanks !

**Comment by dadokkio** [comment]
In our case we added volatility in our requirements in this way:

```
-e git+https://github.com/volatilityfoundation/volatility3.git#egg=volatility volatility3
```

A better release approach would be nice, since using docker we cannot guarantee that, when we rebuilt out images, new pulls are still 100% compatible with our code :innocent:

**Comment by Wenzel** [comment]
Hey @dadokkio , thank you very much !

I had no idea this syntax exited for `requirements.txt`
Note that you can pinpoint a specific commit, tag or branch:
https://stackoverflow.com/a/35998253/3017219

I had to tweak the line a little bit, otherwise `pip install` would throw an error like this:
~~~
    ERROR: Command errored out with exit status 1:
     command: /home/wenzel/Projets/xxx/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8xvr9bpm/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8xvr9bpm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-8xvr9bpm/pip-egg-info
         cwd: /tmp/pip-req-build-8xvr9bpm/
    Complete output (1 lines):
    error in oswatcher setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'-e git+h'"
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
~~~

Fixed with this syntax (pinned to the current commit on master)
~~~
volatility @ git+https://github.com/volatilityfoundation/volatility3.git@0d4075355a6fa16c982b7206bcfcd7132d9afad7#egg=volatility
~~~

But of course having an official package on PyPI would be better :)

**Comment by ikelos** [comment]
Hi there, thanks for your interest in this.  We've only made one official release (actually a pre-release for developers) and a lot's happened to the code since then so we can understand the desire to see a release.  At the time of the pre-release we hadn't managed to get access to the volatility3 name under pypi; luckily someone from the community registered it for us, and it's since been transferred to our control.

We're hoping to have the first official release soon (in the timescale of a few months), but due to a major code change which we want to ensure goes smoothly, we've pushed the code freeze and release back slightly.  We still need to get the packaging finalized, but sorting that is one of the goals during the code freeze period.  Our intention is to package it through pypi when we make the first release.  We're trying to use semantic versioning to allow people to guarantee that targetting a specific version of volatility will ensure it always works (for that reason our first release probably won't be 1.0.0), and we're also looking at automating the process so that tagged commits will automatically produce the appropriate packages.  I hope this gives you enough information to be getting on with and we'll keep trying to push the code forward as quickly and safely as we can.  5:)

The requirements trick is nice, thanks for that @dadokkio!  5:)

**Comment by garanews** [comment]
We too are using this way for [Orochi](https://github.com/LDO-CERT/orochi)    :)

![image](https://user-images.githubusercontent.com/16938405/96473163-95bfbb00-1231-11eb-99e6-f865e00c9516.png)

**Comment by frispete** [comment]
And to get a wider testing of volatility3 on current systems, issues like https://github.com/volatilityfoundation/dwarf2json/issues/24  should be addressed before a release. 

This is especially true due to such systems have phased out Python2 support mostly already..

**Comment by ikelos** [comment]
Just so everyone's aware, there has now been a pypi release of `volatility3` (actually on February 1st) and as such I'm going to close this issue.  5:D
