### ISSUE TITLE
objects: maximum recursion depth exceeded on copy

### ISSUE THREAD

**Issue by Wenzel** [volatilityfoundation/volatility3#358]
**Describe the bug**
Copying a Volatility3 object can lead to an inifinite recursion

**Context**
Volatility Version:  `0d4075355a6fa16c982b7206bcfcd7132d9afad7`
Operating System:  `Ubuntu 20.04`
Python Version:  `3.8.5`
Suspected Operating System:  Windows 7

**To Reproduce**
Download the following [script](https://gist.github.com/Wenzel/76927fb8a4f78fa3fa9a6f51a62f0c14)

1.`python3 bug.py win7.dump`

**Expected behavior**
The script should have converted my dataclasses to dict

**Screenshots**
![Capture d’écran de 2020-10-18 00-43-25](https://user-images.githubusercontent.com/964610/96354798-fdafbd80-10da-11eb-947f-c8d03282cffb.png)

Thanks !

**Comment by ikelos** [comment]
Thanks, this was because the code we used to allow attributes to be accessed on pointers and structs in general always expected to have been initialized properly.  This is not the case in certain situations (such as deepcopy or pickling) where `__setstate__` is called to initialize the (python) object.  This should have been fixed in the commit mentioned above, please feel free to reopen this if you still experience the issue...  5:)

**Comment by Wenzel** [comment]
I confirm that it works, thank you very much !

I wasn't expecting a fix tonight :-)

Thanks @ikelos o/

**Comment by ikelos** [comment]
It was an interesting problem, happy to help.  5;)
