### ISSUE TITLE
Using volatility as library

### ISSUE THREAD

**Issue by MarkoMark98** [volatilityfoundation/volatility3#361]
Good evening, I'm trying to use volatility as a library, but I'm falling in some problems.
`from os import path
import sys
sys.path.append(path.abspath('./volatility3'))
from volatility3.volatility import framework
from volatility3.volatility.framework import contexts
from volatility3.volatility.framework.plugins.windows import pslist

dump_path = '/media/sf_SharedFolder/dumps/2gb/memdump.mem'

framework.require_interface_version(1, 0, 0)
ctx = contexts.Context()
config_path = path_join('./volatility/framework/plugins/', pslist.PsList.__class__.__name__, '-r json -f '+dump_path)
context.config['pslist.PsList.__class__.__name__.-r json -f '+dump_path] = value`

This is the code of my script and I have 2 questions about it:
1.  Are the import right? I mean, the way wich I import the modules is right?
2. I can not understand if my last two code row are right, what's the path_join function? And his inputs are right? Same for context.config[].

By the way the previous code give me the following error:
![image](https://user-images.githubusercontent.com/52664407/96772060-dc084c00-13e2-11eb-871a-91c2aef6cb3b.png)

Please help me, I'm stuck and I don't know how to fix that.

**Comment by ikelos** [comment]
Hi, whilst we will answer questions on the issue tracker, we'd much prefer that you join our slack (https://www.volatilityfoundation.org/slack) to ask questions.  It would allow other members of the community to answer the questions and learn from the answers.

To answer your questions:
1. The pslist plugin should be imported as `from volatility3.volatility.plugins.windows import pslist`, since volatility.plugins is the namespace that all plugins live under.  All the framework plugins will be there as well, but we separate them to keep the core plugins separate from user written plugins, but allow both to be used interchangably.
2. The config path is not a file -path, and has nothing to do with the running of the command.  If you just want to run the volatility CLI, you should use `subprocess.run` or similar.  In this context `config_path` is that name within the configuration tree (so should be something like `plugins.pslist.pid` or similar.

It doesn't sound like you're attempting to interface with volatility through python, but instead trying to run the CLI directly?  If that's all you're after, I'd strongly suggest you investigate `subprocess.run`: https://docs.python.org/3/library/subprocess.html#subprocess.run

Again, the bug tracker isn't the right location for a conversation, so please join the volatility slack channels and we'll be happy to help more there.  5:)  I'll mark this as closed since the question has been answered...
