### ISSUE TITLE
module 'volatility.framework.symbols.windows.extensions' has no attribute 'pe'

### ISSUE THREAD

**Issue by MarkoMark98** [volatilityfoundation/volatility3#366]
I'm trying to use volatility as a library, in my script I can run the plugin, but when I call the populate function on the grid passing in the visitor function, this error occurs:
![image](https://user-images.githubusercontent.com/52664407/97243616-01d48d00-17f7-11eb-81cd-e43f742c6bf8.png)

Volatility Version:  3.0
Operating System:  Kali Linux
Python Version:  3.8
Suspected Operating System:  Windows

```
for column in grid.columns:
    print(column.name)

def visitor(node, _accumulator):
    print("*" * max(0, node.path_depth - 1), end = " ")
    for column_index in range(len(grid.columns)):
        column = grid.columns[column_index]
        print(repr(node.values[column_index]), end = '\t')

    print('')
    return None

grid.populate(visitor, None)
```

This is the code of the visitor function and the calling of populate function.

**Comment by ikelos** [comment]
So, as a follow up to this, it looks like it's because you don't necessarily do the same extensive imports in your code as we do in the CLI.  I think that's probably our fault, it looks like we accidentally import these when we're importing the available layers, but so the plugins can work as-is, it should be explicit.  We do want the code to be used as a library, so if you spot any more of these, do please let us know.  5:)
