### ISSUE TITLE
List `pycrypto` as dependency

### ISSUE THREAD

**Issue by presianbg** [volatilityfoundation/volatility3#377]
**Is your feature request related to a problem? Please describe.**
I was trying to use volatility v3 with a python venv and `lsadump` was not working:
```
volatility: error: argument plugin: invalid choice lsadump (choose from banners.Banners, configwriter.ConfigWriter, frameworkinfo.FrameworkInfo, isfinfo.IsfInfo, layerwriter.LayerWriter, linux.bash.Bash, linux.check_afinfo.Check_afinfo, linux.check_creds.Check_creds, linux.check_idt.Check_idt, linux.check_modules.Check_modules, linux.check_syscall.Check_syscall, linux.elfs.Elfs, linux.keyboard_notifiers.Keyboard_notifiers, linux.lsmod.Lsmod, linux.lsof.Lsof, linux.malfind.Malfind, linux.proc.Maps,.....
....
```

**Describe the solution you'd like**
After few hours I saw that the tool can be run with `-vv` and the DEBUG output was helpful:
```
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.lsadump based on file: windows/lsadump
```
Then installed `pycrypto` with `pip install pycrypto` which solved the problem.

**Describe alternatives you've considered**
I switched back to v2 to complete my task.

**Comment by ikelos** [comment]
Thanks for filing this issue, and sorry that it caused you some trouble.  We do already list pycrypto as an optional dependency (see https://github.com/volatilityfoundation/volatility3/blob/master/setup.py#L38) and we'd like to keep it that way because it's only strictly necessary for a very small number of plugins.  If you don't have pycrypto (or other dependencies that specific plugins require) it will tell you that at the end of the output for `--help` and suggests using `-vv` to figure out what the issue is:
```
The following plugins could not be loaded (use -vv to see why):
volatility.plugins.windows.cachedump, volatility.plugins.windows.hashdump,
volatility.plugins.windows.lsadump
```

It's not clear what else we could do to highlight this, but if you have any suggestions that might help people find the information more easily, we'd be happy implement them?

**Comment by presianbg** [comment]
@ikelos  my bad, I did not checked the `setup.py`.
Now I feel stupid for opening this issue.
Thanks for the awesome tool and the cool project!

**Comment by ikelos** [comment]
No problem at all, we really want to make the tool as usable as possible, so if you spot anything else like this do please let us know!  5:)

**Comment by frispete** [comment]
Allow me to add, that using `pycrypto` is strongly discouraged, because it isn't maintained since 7 years.

Given that a maintained replacement exist: `pycryptodome`, there's no reason to stick with `pycrypto`.

**Comment by ikelos** [comment]
Sure, but I thought since pycryptodome fulfilled the dependency of pycrypto, you just put pycrypto as the requirement?  If I've been doing that wrong or it won't ever pull in pycryptodome that way then I'll definitely change it, just let me know  5:)

**Comment by frispete** [comment]
Yes, you're doing this correctly of course. I only choked on `pip install pycrypto`. Sorry @ikelos.

`pycryptodome` provides the `Crypto` namespace and is designed very carefully to only deviate from the original API, where overwhelming technical or security reasons push for it.

**Comment by ikelos** [comment]
Ok, no problem, I just wanted to make sure we were getting it right.  Thanks for the extra pair of eyes!  5:)

**Comment by presianbg** [comment]
I have installed `pycrypto`  because I'm a newbie and didn't know that its old and unsupported.
If I remember correctly I also tried to install  just `crypto` which did not worked ... 
After reading your comments @frispete   I tried to use `pycryptodome`, but there was some errors for `RC4` (not sure). 

I messed my setup and need to try again only with `pycryptodome`.

**Comment by frispete** [comment]
> I have installed `pycrypto` because I'm a newbie and didn't know that its old and unsupported.

Yep, that's why I spoke up.

> If I remember correctly I also tried to install just `crypto` which did not worked ...

You probably want to do it this way: `pip install volatility3[crypto]`

> After reading your comments @frispete I tried to use `pycryptodome`, but there was some errors for `RC4` (not sure).
> 
> I messed my setup and need to try again only with `pycryptodome`.

You should uninstall `pycrypto` beforehand. It's known to produce hard to explain failures if having both packages installed in one setup. Try this before you restart your setup from point zero. Good luck.
