### ISSUE TITLE
pdbconv: ntkrnlmp.pdb value hardcoded as PDB metadata

### ISSUE THREAD

**Issue by Wenzel** [volatilityfoundation/volatility3#381]
**Describe the bug**
There is a hardcoded value in the metadata of the IST profile produced by `pdbconv.py`
~~~JSON
  "metadata": {
    "format": "6.1.0",
    "producer": {
      "datetime": "2020-11-26T19:03:07.053093",
      "name": "volatility3",
      "version": "1.2.1-beta.1"
    },
    "windows": {
      "pdb": {
        "GUID": "C7D1078904A5908D69236C3A865590A8",
        "age": 3,
        "database": "ntkrnlmp.pdb",
        "machine_type": 34404
      }
    }
~~~

the `ntkrnlmp.pdb` value is hardcoded in [`pdbconv.py`](https://github.com/volatilityfoundation/volatility3/blob/master/volatility/framework/symbols/windows/pdbconv.py#L496)

It should instead refer to the PDB filename currently processed.

Thanks !

**Comment by ikelos** [comment]
Ok, we now try to figure out the right pdbname from the pdb file itself, but it's usually set based on the provided pattern.  It will *not* take it from the filename if a pdb file is directly provided, but instead will attempt to extract it from the IPI stream (which isn't present in every pdb file).  Since we know the pattern in vol3, we should always use the right name in generated JSON within the program.  That's about the best we can do...  5:S
