### ISSUE TITLE
Using symbols in an offline environment

### ISSUE THREAD

**Issue by MaxZabuty** [volatilityfoundation/volatility3#432]
I need to use Volatility3 in an offline environment and I have many different types of  windows machines which I will be analyzing their memory, therefore I will need different symbols.
I have downloaded the Symbols zip you have provided, however, it obviously does not provide all of the symbols needed.

According to Microsoft Docs, the offline symbol packages for Windows are no longer being provided.
Do you have any suggestion on how will I be able to download all the symbols?
Also, how often will you be updating your zip, if at all?

**Comment by ikelos** [comment]
Hi there, thanks for your question.

At the moment volatility doesn't really have scope for dealing with multiple memory images at once, so there's no simple way to ask volatility to try to download lots of symbols at once.  There is support for downloading and processing symbols based off a PDB's name, guid and age (for example `PYTHONPATH="." python volatility/framework/symbols/windows/pdbconv.py -p ntkrnlmp.pdb -g D0C5D8ADE43C099C549CFC2BE23ADB2C1`).  If you already have the pdb files, you can process them the same way `python volatility/framework/symbols/windows/pdbconv.py -f /path/to/ntkrnlmp.pdb`  We don't yet provide a means for easily extracting the name/guid/age from a memory image so it sounds as though there's a couple of enhancements that could come out of your question:

* Provide the name/guid/age needed in a machine readable form for an image when downloading fails
* Provide a means to let volatility process multiple images without needing to use external scripting

I suspect that the first enhancement will be quick and easy to achieve, but will still require some manual effort to gather together the lines that need to be run to get the JSON files needed.  As to the second, I think that will take more thought/consideration although I think it can be done entirely in the CLI.  The difficulty will be ensuring that the errors are collected and displayed once at the end, so that the list of commands needed to populate missing JSON files can just be taken and run elsewhere.  This may take more time to implement...

As to how often we update the zip file, it's not clear, that's simply a corpus that's been built-up over time and we haven't yet reached a conclusion as to the best way to maintain it (or let the community help us maintain it).  Hopefully that will follow after the next release.

**Comment by MaxZabuty** [comment]
> Hi there, thanks for your question.
> 
> At the moment volatility doesn't really have scope for dealing with multiple memory images at once, so there's no simple way to ask volatility to try to download lots of symbols at once. There is support for downloading and processing symbols based off a PDB's name, guid and age (for example `PYTHONPATH="." python volatility/framework/symbols/windows/pdbconv.py -p ntkrnlmp.pdb -g D0C5D8ADE43C099C549CFC2BE23ADB2C1`). If you already have the pdb files, you can process them the same way `python volatility/framework/symbols/windows/pdbconv.py -f /path/to/ntkrnlmp.pdb` We don't yet provide a means for easily extracting the name/guid/age from a memory image so it sounds as though there's a couple of enhancements that could come out of your question:
> 
> * Provide the name/guid/age needed in a machine readable form for an image when downloading fails
> * Provide a means to let volatility process multiple images without needing to use external scripting
> 
> I suspect that the first enhancement will be quick and easy to achieve, but will still require some manual effort to gather together the lines that need to be run to get the JSON files needed. As to the second, I think that will take more thought/consideration although I think it can be done entirely in the CLI. The difficulty will be ensuring that the errors are collected and displayed once at the end, so that the list of commands needed to populate missing JSON files can just be taken and run elsewhere. This may take more time to implement...
> 
> As to how often we update the zip file, it's not clear, that's simply a corpus that's been built-up over time and we haven't yet reached a conclusion as to the best way to maintain it (or let the community help us maintain it). Hopefully that will follow after the next release.

Thank you very much for the quick and professional comment.
I've tried to manually download the pdb files just like you told me. The pdbconv.py was not enoguh though,
I had to use some of the pdbutil code in order to change the name (splitting the age with '-') and then archiving it
using "lzma" module in order to get the perfect output, with ".json.xz", just like you do.

Also, I managed to achieve the first enhancement just like you instructed me.
I wish there was a way to get all the pdb names/guid/age available so I could loop through all of them
and make my own windows.zip symbol archive containing all the windows symbols that will ever be needed, so I don't need
to extract the guid from every image provided to me.
This could have come handy because downloading new symbol everytime I encounter a new guid from a memory sample is a big deal for my company.

**Comment by ikelos** [comment]
My pleasure.  That's another enhancement we can make, such that pdbconv.py outputs to the write filename/path by default (it wasn't designed to be a well known tool, but if it's starting to be used that way we should improve it).

Yes, I added commit `f5504e19` to the develop branch to hopefully help with that.  If you have a different solution, feel free to add it to a branch and submit a pull request.  5:)

As to enumerating all possible kernel GUID/ages, that's difficult to achieve, and we've also seen that Microsoft sometime change old PDB files (meaning regenerating JSON files based on current PDB files won't work, whereas using the old ones it will).  We haven't had any thoughts around building a library, but there has been discussion surrounding keeping a library of windows and linux JSON files.  The largest problem is ensuring all the data is in the right format and contains enough information (since regenerating all data if a mistake is found would likely be infeasible).

I fully understand your plight, but I'm not sure there's a great deal we can do to support that use case other than the slight easements that I've mentioned.  If you have suggestions or ideas, or wish to start a community project to help solve the problem, please let us know and we'll provide what support we can...  5:)

**Comment by MaxZabuty** [comment]
> My pleasure. That's another enhancement we can make, such that pdbconv.py outputs to the write filename/path by default (it wasn't designed to be a well known tool, but if it's starting to be used that way we should improve it).
> 
> Yes, I added commit `f5504e19` to the develop branch to hopefully help with that. If you have a different solution, feel free to add it to a branch and submit a pull request. 5:)
> 
> As to enumerating all possible kernel GUID/ages, that's difficult to achieve, and we've also seen that Microsoft sometime change old PDB files (meaning regenerating JSON files based on current PDB files won't work, whereas using the old ones it will). We haven't had any thoughts around building a library, but there has been discussion surrounding keeping a library of windows and linux JSON files. The largest problem is ensuring all the data is in the right format and contains enough information (since regenerating all data if a mistake is found would likely be infeasible).
> 
> I fully understand your plight, but I'm not sure there's a great deal we can do to support that use case other than the slight easements that I've mentioned. If you have suggestions or ideas, or wish to start a community project to help solve the problem, please let us know and we'll provide what support we can... 5:)

Thank you very much for the help, you've provided me all the solutions that were needed.
