### ISSUE TITLE
Potential confusion in the API regarding symbol offsets

### ISSUE THREAD

**Issue by ikelos** [volatilityfoundation/volatility3#488]
This is to keep track of how we deal with a potential confusion that got introduced to the API.  There was a direct request to allow all symbols in a particular symbol table to be shifted by a fixed amount, there was also a separate request for a `module` which would construct an object based on a symbol with the module at the offset *within the module*.  We implemented both mechanisms.  We allowed the module to be created with a 0 offset if necessary, in which case no symbol addresses change.  What that gives us is two ways that the symbol addresses may get modified for a module, and this could lead to the change being added twice, causing confusion.

Mechanism A: 
Load symbol table with `symbol_shift` by `module_offset` amount 
* All symbol addresses come out as `symbol_address + module_offset`

Mechanism B:
Construct module with `module_offset` as parameter
* symbols and their addresses come out as they were in the symbol table
* objects created using `module.create` have the `module_offset` added to them automatically

Trouble condition:
Module constructed with `offset` parameter, then symbol table created with `symbol_shift` parameter, then object constructed using module
* Outcome: object constructed at `symbol_address + module_offset + module_offset`

This feels like we messed up.  The module mechanism was supposed to be handy, but we wanted the data only to be changed as needed (on use) and for the symbol addresses to be exactly what's been read from the data.  The `symbol_shift` was strongly requested and is now deeply embedded in the linux system, due to ASLR (rather than having to add the ASLR value to every symbol).

I'm not sure how best to resolve this, the big unknown is whether symbol addresses for a module will ever be used *without* adding the module offset to them?  If not, I suggest we deprecate the `offset` value of the module interface (checking there's no other use cases for what it provides) and move to `symbol_shift` as the preferred mechanism.  If there are cases where you might need the original symbol address value, then we need to figure out what we're gonna do and how we're gonna avoid it all getting thoroughly confusing for people.

@npetroni I'm after your critical logic first, but @iMHLv2 and @atcuno I wanted you both to be in the loop in case you've got a preference over how this is resolved...

**Comment by atcuno** [comment]
The current API is definitely confusing to me.

This function, which I know you commented about on the skeleton key ticket, seems very strange to me:

https://github.com/volatilityfoundation/volatility3/blob/f1d7d8610a62735cd382f6b68d3508873a5b8caf/volatility3/framework/plugins/windows/skeleton_key_check.py#L171

I instantiate a module at an offset but then still have to add the address to get_symbol().address. Also, making offset 0 seemed to work the same as non-zero.

There also seems to be two different things addressed in the ticket.

1) The symbol_shift is for ASLR in the kernel. I can't think of any reason why someone would want the unshifted address since it wouldn't point to the correct data in that particular memory sample. It really can only lead to programming errors and broken analysis. This is why it happens auto, otherwise every plugin would have to add the shift, and they would all end up looking like the function I linked to. It also seems like a pain for volshell users... a common task I do in volshell is explore new data structures by using get_symbol (of Volatility 2) which returns the shifted address. I can then db() dis() etc. 

2) The situation like I have for the skeleton key check plugin, where I know where a module is in the virtual address space and then want to get the full runtime address of the symbol. As I said earlier in this comment, having offset = <runtime address> in the constructor and then having that auto added on get_symbol().address seems much more reasonable to be since that gets you the actual data.

Also, the naming convention of having '.address' return an offset inside the file was confusing to me at first. If we want to preserve the ability of people to get the offset inside the file, then it seems better to have something like get_symbol().offset for that and then .address could be the full runtime address. Right now .address doesn't actually return an address unless I really missed something.

**Comment by ikelos** [comment]
So the way a `module` was supposed to work, is that you give it an `offset` and then calling `object` or `object_from_symbol` on it, would automatically shift the offset of that object into the module: https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/contexts/__init__.py#L171

It doesn't change symbols, because the value of the symbols *shouldn't* change (which is why I wasn't keen on the shift mechanism we came up with for symbol tables).  It also doesn't change types or anything else, it's only used to keep track of a module and allow objects to be constructed in the module without needing to worry about the offset.

I think the stumbling point we've come across at the moment is that the type information (hand made) is stored in a different symbol table to the symbol (generated from a PDB).  There's no real way of injecting a type into an existing table (at least, not something that isn't horribly hacky and breaks several unwritten assumptions about the JSON never changing from instantiation).  So to use the module mechanism.  You could use `module.object('othertable!symbol')` to do it, but I don't recall whether array subtypes have to be objects or can be string names....

Loading the kernel symbol_table with the shift does make a degree of sense, otherwise every plugin needs to pluck the appropriate ASLR values from somewhere, and that would end up being some kind of metadata place which would get ugly quickly.  I'm still not a fan of symbol values being different to the data they were made with though (it locks symbol tables to a particular loaded module, which was never how they were supposed to be used and could lead to accidents where the same JSON is loaded into different tables, just to give them different offsets, which is exactly what the module object was supposed to do).  But we should make a judgement call and try to reduce these things down to a single way of doing them.

I guess what I'm saying is that the symbol value should unambiguously be the value that was read from the source data, and then the `module` constructed on the offset should be how that's used.  I could think about adding a `get_symbol_address` but I really *really* don't like the idea of changing the data a symbol provides, it goes against the mental model of what people understand a symbol to be in order to fit a single particular situation we're facing.

We agreed on symbols having a name and an address, specifically because `offset` wasn't deemed as accurate as a description for what was stored there as `address` (offset is seen relative to something, address is an absolute value).  Since it wasn't possible to say that a symbol would always be relative to the file it came from, address was chosen.  I don't think we can change that now, the time for doing that was when we discussed and decided it I'm afraid.

**Comment by ikelos** [comment]
Forgot to update this as we made decisions, but we've moved to a ModuleRequirement for plugins that need a functioning kernel, and that should have the shift set by automagic.  We're looking to deprecate the old symbol_shift code in version 2.0.0, but we'll probably also jigger around with the Module class and make it actually configurable rather than the current bolt-on of a `ConfigurableModule` so that people can still use the old one without configuring it.  This would be an API break though, so will be saved for 2.0.0

**Comment by ikelos** [comment]
This has been resolved by #538 and #551 so marking as closed.
