### ISSUE TITLE
AttributeError trying to get a type member prefixed by double underscore from other class methods

### ISSUE THREAD

**Issue by gcmoreira** [volatilityfoundation/volatility3#522]
When calling a type member from a class method and the type member's name is prefixed by a double underscore (a private keyword for Python) the framework won't be able to find that attribute.

That behavior can be reproduced with the following code:
```python
#!/usr/bin/python3 
class A:
    def __getattr__(self, name):
        print(name)

class B:
    @classmethod
    def blah(cls):
        A().foo
        A().__bar

A().foo
A().__bar

B.blah()
```

The above doesn't return:
```
foo
__bar
foo
__bar
```

But the following:
```
foo
__bar
foo
_B__bar
```

Python is mangling the attribute's name and calling _\_\_getattribute\_\__ and _\_\_getattr\_\__ with it prefixed by the class name. So, the attribute **__attrname** will be  **_classname__attrname** in those methods.

In vol3, the issue is in [AgregateType](https://github.com/volatilityfoundation/volatility3/blob/af090bf29e6bb26a5961e0a6c25b5d1ec6e82498/volatility3/framework/objects/__init__.py#L733) where under these circumstances and trying to access a type member like [this](https://github.com/torvalds/linux/blob/62fb9874f5da54fdb243003b386128037319b219/include/net/sock.h#L354), the framework won't be able to find that attribute.

Below is my attempt to fix this issue. Basically, it strips the _\_classname_ prefix from the attribute's name ONLY when this is called from a class method. It works in my tests but would like to hear your thoughts about it before submitting a PR.

The fix requires using the Python inspect module to get the call stack.

```diff
diff --git a/volatility3/framework/objects/__init__.py b/volatility3/framework/objects/__init__.py
index 2f282965..7f840598 100644
--- a/volatility3/framework/objects/__init__.py
+++ b/volatility3/framework/objects/__init__.py
@@ -6,6 +6,7 @@ import collections
 import functools
 import logging
 import struct
+import inspect
 from typing import Any, ClassVar, Dict, List, Iterable, Optional, Tuple, Type, Union as TUnion, overload
 
 from volatility3.framework import interfaces, constants
@@ -732,6 +733,21 @@ class AggregateType(interfaces.objects.ObjectInterface):
 
     def __getattr__(self, attr: str) -> Any:
         """Method for accessing members of the type."""
+
+        frame_locals = inspect.stack()[1][0].f_locals
+        if 'cls' in frame_locals:
+            # When this is called from a class method using an attribute name with private name syntax i.e. __attrname,
+            # Python replaces the attribute's name '__attrname' for '_CLASSNAME__attrname'.
+            # If a type has a member with this syntax, we won't be able to find the attribute. A concrete example:
+            # https://github.com/torvalds/linux/blob/62fb9874f5da54fdb243003b386128037319b219/include/net/sock.h#L354
+            # The code below strips the '_CLASSNAME' prefix from the attribute's name only when this is called from
+            # a class method.
+            calling_cls = frame_locals['cls'].__name__
+            class_prefix = "_{class_name}".format(class_name=calling_cls)
+            attr_prefix = "{class_prefix}__".format(class_prefix=class_prefix)
+            if attr.startswith(attr_prefix):
+                attr = attr[len(class_prefix):]
+
         if attr in ['_concrete_members', 'vol']:
             raise AttributeError("Object has not been properly initialized")
         if attr in self._concrete_members:
```

**Comment by ikelos** [comment]
Hiya, thanks for the contribution!  There's a few points to be made here:

First off, it's already possible to access members with a specific naming using the [`.member`](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/objects/__init__.py#L729) method which won't do the automatic renaming, and so should let you lookup any member that isn't overridden by a concrete implementation in the class.

Secondly, the code seems to go to an awful lot of trouble, and doesn't seem well guarded.  Most of the looking up stack frames will be pointless in 99% of the cases, so it definitely wants to be behind an `if '__' in attr` guard at a minimum.  There also then isn't necessarily much point in looking up the class, we don't want to use it, we just want to chop it off it it's in there, so I'd suggest at most checking for `_blah__whatever`, then maybe an `instance(self, blah)`, before doing the actual lookup on `__whatever`.  Also, all this should be *after* the concrete_members lookup, otherwise an object could come long with something strange (I'm worried about things like `__new__` and other special methods) and override them.  Python comes first, if necessary we can make the member method hold the lookup code, and have `__getattr__` call member to do the lookup.

So the idea sounds fine, with the caveats that there may well be certain things that python requires which we can never override nicely (and there should be the `.member` method for that, if it doesn't work properly, that's the bit that should be fixed), and that it needs to be efficient, so only do heavy lifting if it's necessary.  I'm not sure trying to extract the current class if worthwhile, rather than a bit of string manipulation and verify that we're of that type of class?

Hope that's the kind of feedback you were after?

**Comment by gcmoreira** [comment]
Hey,
Thanks @ikelos for the comments.

The code does check for the __ already but not just the __ but also the specific calling class:
```python
    class_prefix = "_{class_name}".format(class_name=calling_cls)
    attr_prefix = "{class_prefix}__".format(class_prefix=class_prefix)
    if attr.startswith(attr_prefix):
      ...
```
Basically, it's checking for a _\_classname\_\__ prefix, but replacing _classname_ with the actual calling class name.

With that I want to prevent the case of a type member having the format _\_foo\_\_bar_
but it wasn't python the one prepending  _foo but it's actually the type member's name.

IMO checking for \_\_  (if '\_\_' in attr)  won't be appropriate, as it could match other false positives like _foo\_\__ or _foo\_\_bar_, including calling the same type member _\_\_bar_ from a class instance in which case we don't want to do anything.

Do you mean I should check that twice? Like:
```python
    if 'cls' in frame_locals:
        if '__' in attr:
            ...
            if attr.startswith(attr_prefix):
```

Lastly, I didn't get what you said with _instance(self, blah)_, do you mean isinstance()? if so, the caller is a class method, not an instance method. But maybe you meant to check for the opposite, not sure. Could you please write a small example explaining this?

**Comment by ikelos** [comment]
I'm not sure you got the point I was making.  If we zoom in and look at each of these in depth, let's say that doing *anything* costs 1 unit of time (some cost substantially more than others, but for now, let's say they all cost the same).

In my example, in 99% of cases, we'll do one test, it'll say `__` isn't in the attr, and we move straight on.  Total cost 1 unit of time
In your example, in 100% of cases you call out to `inspect.stack()`, then access an array element (twice) and do an assignment, then you check an if statement.  That means that before we've even had the possibility of deciding whether or not we need actually do something, we've used up 5 times as much time.  You're checking all the right things but you're doing it even when it's obviously unnecessary, so it's really inefficient.  Accessing an object attribute, within volatility, can happen millions of times in a run, so every millisecond added to that code needs thinking about.  That's why I'd start with a simple `__` check before you do *anything* else.  In 99% of cases, there won't be a `__` and figuring out the class will just be a waste of time.  It absolutely could match false positives, and it will be checking the same thing twice, but importantly, it'll only be doing so in a very, very, very small number of cases.  So the point is to cut the numbers down as quickly and easily as possible.  If `__` isn't in the attr name then the rest of the work will _never_ be useful, if it is, then we need to do further checks...

I did mean `isinstance`, but  `def __getattr__(self, attr: str)` isn't an `@classmethod`, so we can use `self`?  It's not clear how or when that could get called as if it were a classmethod, but should we need to, we can use `issubclass` as well.  All we're trying to do is verify whether we should be chopping something off and trying a look-up.  We cannot *ever* cover every situation, because some structure may have a name that exactly matches an attribute that volatility objects have (`.vol` for instance).  Rather than writing a bunch of code to almost handle it in most case, I'm happy to simply require that the caller understand that issue and use `.member` to get to it.  Again, we can rejig `.member` so that it always does the lookup, rather than potentially hitting a python attribute, but that requires some consideration around properties...

Lemme know if any of the needs clarification?  I don't think we're suggesting different things, I'm just saying that the proposed way of making the change is inefficient and will need reworking before it gets applied...

**Comment by gcmoreira** [comment]
re  `__` : I think I got your point and agree. You want to avoid the `inspect.stack()` call in 100% of the cases. Good, like below:
```python
    if "__" in attr:
        frame_locals = inspect.stack()[1][0].f_locals
        if 'cls' in frame_locals:
            ...
            if attr.startswith(attr_prefix):
```

**Comment by gcmoreira** [comment]
re `isinstance`: I mean, the caller is a classmethod, as `blah` in the first example. 
And there are no subclasses here, so not sure how `issubclass`  could help this in the example provided.

I do understand there may be other workarounds to access a type member. Now, naturally, the first thing everyone will try is `type_object.type_member`. It could take a while until you understand why accessing exactly the same _type member_ from a _class instance method_ and from a _class method_ could work differently. 
IMO and from the framework user perspective, it should be transparent to the user.

**Comment by gcmoreira** [comment]
Yeah, I think we are on the same page. After all, for a good reason, it's just an issue ticket and not a PR ;) ... I knew it would require a fresh pair of eyes. Anyway, I'm happy with any other way to fix this and also happy that you are aware of this limitation :)

**Comment by ikelos** [comment]
> re `isinstance`: I mean, the caller is a classmethod, as `blah` in the first example.
> And there are no subclasses here, so not sure how `issubclass` could help this in the example provided.

Sorry, in my head I'd converted the string to a class, so we could test it, but you're right.  I'm not sure we could just do a string comparison on `self.__class__.__name__` either
 
> I do understand there may be other workarounds to access a type member. Now, naturally, the first thing everyone will try is `type_object.type_member`. It could take a while until you understand why accessing exactly the same _type member_ from a _class instance method_ and from a _class method_ could work differently.
> IMO and from the framework user perspective, it should be transparent to the user.

I'm getting thoroughly confused.  I'm gonna have to reread what you've written, because there isn't a classmethod in sight?  You can ask for the attribute of an instantiated struct object, because once instantiated it has an offset and a layer and can give you other objects.  Before it's been instantiated, it can't give you those things, so asking the class for something doesn't make sense?   The thing before an object is created is called a Template, and that's a totally different class, and not all objects have members, therefore templates don't have scope for it either.

Putting classmethods to one side, because whilst I know what a class method is, we don't use them in any standard objects... I think we can make it so that you could ask for a member that starts with `__`, but I'd need to see an efficient PR as suggested, and I'd need to think through the consequences of doing it.  As such, I'm gonna leave this open for a while in case a PR comes along that we can point at it...  5:)

**Comment by ikelos** [comment]
Ok, so what I think you're saying is that if *someone else's code* from a class method, tried to use an attribute, it would get converted by python into a private method (because that's what `__` does).  I've tested the sample you originally provided, and I'm really surprised that `A().__bar` does return `__bar`, I genuinely expected it to have been converted to the name mangled name.

So I think I'm starting to understand the issue.  I wouldn't have expected `volobj.__anything` to ever have worked properly, but this suggests that it would in some cases but not in others.

Alright, so now I've got a much better grasp of the problem (sorry, I've been a bit rushed recently, so I didn't fully process what you were saying), I'd be happy to review another version.  I don't think it needs the inspect module at all though.  I think it would be enough to do something like:

```
if '__' in attr:
  if attr.startswith(f'_{self.__class__.__name__}__'):
    attr = attr[len(self.__class__.__name__) + 1:]
```
I think that `self.__class__.__name__` is what's used to do the private mangling, it wouldn't touch them if they're not called from a classmethod, and it should still be pretty fast due to the guard at the start (although since we're not doing any processing, it'd probably be fine just using the format string to begin with).  One remaining question is whether it goes right at the start, or once we already know the attr isn't in the concrete list.  I'd suggest once we know it's not in the concrete list, but I haven't fully thought it through...

**Comment by ikelos** [comment]
I also think it would be a good idea to move that code out of the existing method and into `member` and then have it call into `member` (making sure member is in the concrete list first, of course).

**Comment by gcmoreira** [comment]
Hehe yeah it's not easy to spot.
But the `__class__` won't work as it is not the class name where  `__gettattr__`  belongs to, but the caller class. 
If you check the output it says `_B__bar`  and not `_A__bar`, that's what I think it's weird. 
I would expect, at least `_A__...`, the instance class name because it's the A's `__bar` that I'm requesting.  So, here:
```
class B:
    @classmethod
    def blah(cls):
        A().foo
        A().__bar      # <---- HERE
```
I'm calling `__getattr__` from an instance of A  `A().__bar`. But the attribute is mangled to `_B__bar`.

We need the caller's class name, if we want to check that name AFAIK the only way to get that is using the stack.

You mean the code below, right?
```python3
#!/usr/bin/python3 
class A:
    def __getattr__(self, attr):
        if '__' in attr:
            if attr.startswith(f'_{self.__class__.__name__}__'):
                attr = attr[len(self.__class__.__name__) + 1:]
        print(attr)

class B:
    @classmethod
    def blah(cls):
        A().__something

A().__something
B.blah()
```
Output:
```python
$ ./test.py 
__something
_B__something
```
It doesn't work.

**Comment by gcmoreira** [comment]
```python
#!/usr/bin/python3 
import inspect

class A:
    def __getattr__(self, attr):

        if "__" in attr:
            frame_locals = inspect.stack()[1][0].f_locals
            if 'cls' in frame_locals:
                # When this is called from a class method using an attribute name with private name syntax i.e. __attrname,
                # Python replaces the attribute's name '__attrname' for '_CLASSNAME__attrname'.
                # If a type has a member with this syntax, we won't be able to find the attribute. A concrete example:
                # https://github.com/torvalds/linux/blob/62fb9874f5da54fdb243003b386128037319b219/include/net/sock.h#L354
                # The code below strips the '_CLASSNAME' prefix from the attribute's name only when this is called from
                # a class method.
                calling_cls = frame_locals['cls'].__name__
                class_prefix = "_{class_name}".format(class_name=calling_cls)
                attr_prefix = "{class_prefix}__".format(class_prefix=class_prefix)
                if attr.startswith(attr_prefix):
                    attr = attr[len(class_prefix):]

        print(attr)

class B:
    @classmethod
    def blah(cls):
        A().__something

A().__something
B.blah()
```
Output:
```
$ ./test.py 
__something
__something
```

**Comment by ikelos** [comment]
That's nuts, apparently name mangling doesn't do anything intelligent based on subclasses or anything, it just *always* takes it from the current class that the call is defined within (whether it inherits or not).  Their example shows why that makes sense during inheritance, but it makes no sense for two classes that aren't related, because defining the new one would be private anyway...

https://docs.python.org/3/tutorial/classes.html#private-variables

Ugh, that makes my brain hurt, and I don't really want to deal with it.  I think I'd let it in even if it were just something like:
```
if '__' in attr and attr.startswith('_') and not attr.startswith('__'):
  attr = attr[attr.find('_', 1):]
```

I really don't think super specific and expensive checking of the class is worthwhile.  There are very specific corner cases (where a linux variable mimics the pattern of `_<thing>__<otherthing>` and we'd turn it into `__<otherthing>`) that would fail, but again I'd let people fall back to the `member` method and ensure that it didn't change the parameter name at all...

**Comment by gcmoreira** [comment]
Yeah, I think that behavior is not well documented.

Sure, that code also works. Although, I would rather check the startwith first:
```
    if attr.startswith('_') and not attr.startswith('__') and '__' in attr:
```
Assuming precedence there will make python to execute that line from left to right.

**Comment by gcmoreira** [comment]
[PR](https://github.com/gcmoreira/volatility3/tree/issue-522-private-attr-name-mangled) created but I now wonder if just in case it would be better to move the if after:
```python
 if attr in ['_concrete_members', 'vol']:
            raise AttributeError("Object has not been properly initialized")
```

**Comment by ikelos** [comment]
Yep, it would, that's the comment I just made.  5;)

**Comment by ikelos** [comment]
Actually, after both the first `if` statements

**Comment by gcmoreira** [comment]
done, thanks

**Comment by gcmoreira** [comment]
Hey ... I realized that the latest version of the fix won't work when the class contains an underscore :)
If the calling class is named `THE_CLASS` it will replace the wrong characters.

```python
#!/usr/bin/python3 
class A:
    def __getattr__(self, attr):
        if  attr.startswith("_") and not attr.startswith("__") and "__" in attr:
            attr = attr[attr.find("_", 1):]  # See issue #522
        print(attr)

class THE_CLASS:
    @classmethod
    def cm(cls):
        A().__something

    def im(self):
        A().__something

    @staticmethod
    def sm():
        A().__something

A().__something
print("")
THE_CLASS.cm()
THE_CLASS().im()
THE_CLASS().sm()

```
Returns:
```
__something

_CLASS__something
_CLASS__something
_CLASS__something
```

I knew we were missing something with that simplification.

* Note also this issue not only happens when it's called from a `classmethod`.

**Comment by gcmoreira** [comment]
I had a look at what inspect is actually doing, and yeah that's probably too much. Also, unfortunately, stack() doesn't return a generator so with the first proposed implementation, we needed to walk the whole stack to then get the frame of the calling function.

Long story short, we only need `sys` and check the calling frame.
```python
    def __getattr__(self, attr: str) -> Any:
        """Method for accessing members of the type."""

        ...

        if attr.startswith("_") and not attr.startswith("__") and "__" in attr:
            calling_frame = sys._getframe(1)
            calling_frame_locals = calling_frame.f_locals
            if 'cls' in calling_frame_locals:
                calling_cls = calling_frame_locals['cls'].__name__
                class_prefix = "_{class_name}".format(class_name=calling_cls)
                attr_prefix = "{class_prefix}__".format(class_prefix=class_prefix)
                if attr.startswith(attr_prefix):
                    attr = attr[len(class_prefix):]
```

Sounds better?

**Comment by ikelos** [comment]
Hiya, thanks for doing the further analysis, but this clearly accesses a private member of `sys` (as indicated by the preceding `_`) which means it could change without warning in the future, so I'm not going to be adding that to every single attribute lookup we do.  I think getting as close as possible will be fine, without needing to provide perfect verification (because as you mentioned, we don't get it right at the moment, so anything will be an improvement).

I'd much prefer time be spent on refactoring the code into the `member` function and verify that all works, than being absolutely 100% certain that a case which won't happen all that often can't be misled by something which will happen even less often.  It just doesn't seem worthwhile?

If you can cut the amount of processing down and keep it behind the guard I'll consider it, but not at the expense of using a private member of a core class to do it...  5:S

**Comment by ikelos** [comment]
As to being too simplistic with `attr[attr.find("_", 1):]`, that's fine, very *very* few classes will include a double underscore, so we can simply search for that...

`attr[attr.find("__", 1):]` 

A simple solution seems far better than masses of complexity for a tiny, tiny corner case...

**Comment by ikelos** [comment]
So if you're happy making the find change to a double __ rather than a single one, we can merge it and see how that goes?

**Comment by gcmoreira** [comment]
It sounds good. Done
Cheers
