### ISSUE TITLE
Linux Plugins not working

### ISSUE THREAD

**Issue by gunner4361** [volatilityfoundation/volatility3#553]
/opt/vol3/volatility3# python vol.py -f /media/ben/Linux/LMG/capture/U-14-2021-08-24_15.35.09/U-14-2021-08-24_15.35.09-memory.lime linux.pslist.PsList
Volatility 3 Framework 1.2.0
WARNING  volatility3.framework.plugins: Automagic exception occurred: KeyError: 'memory_layer'

Unsatisfied requirement plugins.PsList.vmlinux: 
Unable to validate the plugin requirements: ['plugins.PsList.vmlinux']

**Comment by ikelos** [comment]
Thanks very much for reporting this.  We recently made a change to the way requirements for plugins were specified (from separate layer and symbol tables to just a kernel module), but some plugins didn't specify the architectures they needed.  This also highlighted the assumptions made in the symbol finding code that all layer requirements were expected to be architectures rather than physical layers, but the new code allows these to satisfy the requirement.  That was happening and then the symbol finder code wasn't able to try and move a layer down (because there was only one layer).  The commit I've applied is an immediate fix (the image will still cause an error, but this time it should be clearer that it's due to the plugin not being able to find the kernel...

I'll be applying a second fix in a bit to ensure that the automagic fails gracefully if it's given a non-intel layer to work on.  Thanks for spotting it!  5:)
