### ISSUE TITLE
Support AVML Snappy compressed memory images

### ISSUE THREAD

**Issue by votd-se** [volatilityfoundation/volatility3#564]
**Is your feature request related to a problem? Please describe.**
When processing AVML snappy compressed memory captures, Volatility3 generates a set of unrelated error messages which do not reflect the root cause - that Volatility3 needs uncompressed memory captures. 
e.g
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Bash.kernel

Unsatisfied requirement plugins.Bash.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.Bash.kernel']

**Describe the solution you'd like**
Detect if compressed memory captures have been provided to Volatility3 (magic headers for snappy?) and generate an error message:
"The provided memory capture is compressed with Snappy, please decompress the image first" or something to that effect.

**Describe alternatives you've considered**
None considered.

**Additional information**
N/A

Thank you!

**Comment by JeremyNGalloway** [comment]
+1
I wasted a bit of @ikelos time yesterday troubleshooting an issue that was the result of attempting to analyze an image compressed with AVML 🤦

**Comment by ikelos** [comment]
Does anyone have a public image available compressed using AVML?  We might as well support the file format rather than just putting a message.

I would like to point out, however, that they don't appear to have chosen a different extension for a compressed image over an uncompressed one, and it's a little unreasonable to expect volatility 3 to know about and warn about all file formats (those that exist and those that don't yet).  As long as the compression used can be detected by the standard linux file-magic, it should be straightfoward to add support, but getting a copy of an image to investigate would be really useful...

**Comment by JeremyNGalloway** [comment]
@ikelos you make a great point about AVML. I've raised an issue on their project here: https://github.com/microsoft/avml/issues/25#issue-992679818

Having built-in support for snappy compressed images would be fantastic.
I will attach a compressed capture image ASAP.

**Comment by JeremyNGalloway** [comment]
I've just taken a compressed and uncompressed capture of a new machine using AVML (using Amazon Linux 2 AMI (HVM), SSD Volume Type - ami-00dfe2c7ce89a450b (64-bit x86)).
Both files are clearly named and can be downloaded here (1.4Gb total): https://www.transferxl.com/00pDNWz5v063b

**Comment by bmc-msft** [comment]
@ikelos `avml` doesn't specify a file name (or extension), that must be provided by the user.

**Comment by ikelos** [comment]
Thanks for the examples files.  It turns out avml reformats its lime files, but that shouldn't be too much of an issue.  The issue I'm having at the moment is that the defacto python snappy package (https://pypi.org/project/python-snappy/) seems broken, in that it keeps erroring on both the files I made with AVML (after removing the 32-byte AVML header) which uses a rust snappy implementation.  Debugging that's going to be a bigger task than I was hoping, so it won't be done that quickly I'm afraid...

**Comment by votd-se** [comment]
Awesome, AVML snappy compressed lime files support by default would be fantastic! Thank you @ikelos
