### ISSUE TITLE
Volatility stuck at 98% during PdbSignatureScanner

### ISSUE THREAD

**Issue by hackerman008** [volatilityfoundation/volatility3#571]
![Screenshot from 2021-09-23 12-37-35](https://user-images.githubusercontent.com/20148760/134467692-bd8ff1ec-6711-4362-8506-730b206b594e.png)

**Comment by ikelos** [comment]
Hiya,

The first error you're seeing is because you didn't pass the `-f` option before you provided the filename, so volatility believe that the filename was a plugin you wanted to run and let you know that it wasn't a plugin (and provided a list of the possible plugins it could have been).

The second half is more interesting, but you haven't said how long it took before you state that it's frozen there.  You can get more information during the process by adding `-vvv` directly after `vol.py` in the command line.  It may not give you more inormation, but it should show you what it's doing.  It's possible that it's identified and then attempting to download the the necessary pdb file and then convert that into a JSON file that it can use.  This is a one off process when a windows image which you don't have the JSON for is downloaded and processed.  The results are saved, meaning it should be much quicker in the future.

The output from adding `-vvv` should give you more information about what's going on, and I'd give the process at least half an hour before marking it as frozen, just in case.  Please let us know the results of testing with `-vvv` and leaving it to complete for half an hour and we can investigate from there...

**Comment by ikelos** [comment]
There hasn't been a response to this in a while, so I'm going to mark it as closed, please feel free to reopen it if you test it out with `-vvv` and can share the results...
