### ISSUE TITLE
Request for mft plugin

### ISSUE THREAD

**Issue by 108806** [volatilityfoundation/volatility3#573]
- windows.hashdump 
- windows.cachedump
- windows.lsadump
- accessing mft data (can't figure out any way to do it in v3)

I have noticed that in infosec most of the people still tend to use volatility 2 over 3, some compatibility of functionalities would be nice for anyone who wants to make a transition.

**Comment by ikelos** [comment]
It's not quite clear what the issue is?  The specific plugins mentioned are all present:

[hashdump](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/windows/hashdump.py)
[cachedump](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/windows/cachedump.py)
[lsdump](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/windows/lsadump.py)

If you're not able to see them, it's likely due to a missing dependency.  You can find out which plugins are installed but not functional using `vol.py --help` and it should tell you how to get additional information about what's going wrong (`vol.py -vvv`).  In the case of those three plugins, they all rely on pycryptodome, so you probably need to install that before use.

As to the mft data, I don't think we've got an mft plugin so we can add it to #118 for when our team gets time to develop it, but if you'd like to try your hand at it, the documentation for doing so is available at https://volatility3.readthedocs.io/en/stable/simple-plugin.html and https://volatility3.readthedocs.io/en/stable/complex-plugin.html...
