### ISSUE TITLE
QEMU layers are extremely slow

### ISSUE THREAD

**Issue by NiklasBeierl** [volatilityfoundation/volatility3#585]
**Is your feature request related to a problem? Please describe.**
I generate lots of snapshots for validating forensics heuristics. I do that by spinning up qemu-vms and "virsh dump"ing their memory. As volatility points out, working with qemu files is slow, conversion to "raw" files with the `layerwriter` pllugin is the solution. However, running the layerwriter plugin itself is also quite slow, especially if you do it for dozens of snapshots.

**Describe the solution you'd like**
Using `-vvvv` on my vol command, I saw that the plugin spends quite some time with trying different stackers:
```
Level 8  volatility3.framework.automagic.stacker: Stacked QemuSuspendLayer using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 6  volatility3.framework.layers.elf: Exception: Bad magic 0xf000ff53 at file offset 0x0
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsIntelStacker
DEBUG    volatility3.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using MacIntelStacker
INFO     volatility3.framework.automagic.mac: No Mac banners found - if this is a mac plugin, please check your symbol files location
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LinuxIntelStacker
DEBUG    volatility3.framework.automagic.linux: Identified banner: ...
```
As a first speedup I would like to tell the layerwriter plugin to go straight to the LinuxIntelStacker. That could perhaps be achieved with an additional cli option.

**Describe alternatives you've considered**
I could probably go figure into the code and change the order in which the Stackers are attempted, but I haven't gotten around to that yet. I'd highly appreciate hints.

**Comment by ikelos** [comment]
Hiya, it's not overly well documented, but the CLI already allows you to provide a list of the stacker classnames that you want to use, so if you know ahead of time, you can ensure that only the stackers you need are attempted.

```
  --stackers [STACKERS ...]
                        List of stackers
```

I agree it's strange that the qemu layer is so slow, whereas the implementation of the AVML which uses an actual compression library is surprisingly fast.  It makes me think that either some form of caching or something else could be used to make the qemu layer much faster, but for the cursory glance I've taken I couldn't see the efficiency problem.  It may well be worth profiling to figure out where all the time's being spent and then try to optimize that.

If you want to try digging into it, I'd see if you can spot any obvious differences between [the qemu implementation](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/layers/qemu.py#L15) and[ the (more complex) speedy implementation](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/layers/avml.py#L22).  If you need direct pointers or tips, it might be best to grab me on slack rather than filling up an issue with conversation...  5:)

**Comment by ikelos** [comment]
(One thing to point out, is that the list is space separated, which means you'll need another option like -q or similar, before you come to specify the plugin, something like:
```
vol.py -f /path/to/file --stackers QemuStacker -q layerwriter
```
or
```
vol.py --stackers QemuStacker -f /path/to/file layerwriter
```

**Comment by NiklasBeierl** [comment]
> ```
> vol.py -f /path/to/file --stackers QemuStacker -q layerwriter
> ```

Allright, I didn't see that because I only checked for something like that in the `layerwriter` plugins options, not `vol` s options, thanks! 

One thing that I should note for the next person, is that I had to pass both: `LinuxIntelStacker` and `QemuStacker`. 

When only passing `QemuStacker` i got this error: 
```
A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The necessary symbols are present and identified by volatility3
Unable to validate the plugin requirements: ['plugins.LayerWriter.primary']
```
Despite explicitly specifing: `--layers`
```
vol -vvv -s ./debugging-symbols/ --stackers  QemuStacker -f ./snapshot --layers memory_layer
```
and despite getting this log:
```
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['QemuSuspendLayer', 'FileLayer']
``` 
Shouldn't the `QemuSuspendLayer` be sufficient to convert from QEMU -> Raw?
I know this really begs the question of what I want to do with a snapshot if I can not get an IntelLayer for it (i.e. if I don't have debugging symbols). 
But not having debugging symbols is exactly the point of my research. :innocent: 

**Most importantly,** it seems like that did not make the process much faster. It just took 45 minutes to create 4GB raw file from a 653MB qemu file. It appears as tho it "scales" linearly: ~10min /GB of raw file.

**Comment by ikelos** [comment]
Yeah, fair enough.  Since you might want to control the automagic for any plugin, it's a global option not a plugin specific one.

The `TranslationLayer` requirement is what failed, but since it doesn't have any specific architectures, it *should* have passed with only the qemu layer, so I'm not sure exactly why that failed.  The layerwriter should be able to write any layers available, so it would be quite handy if you or I could set that requirement to optional and see if that allows layerwriter to see any and all layers, regardless of the stacker reaching a normal translation layer (to be fair, without the architecture, that's what I thought happened, so I may need to dig further into it anyway).

Yeah, the qemu layer is likely where most of the slow down occurs, but I'm just not certain why...It might be doing a lot of seeking back and forth (particularly if there isn't a map and it needs to traverse the entire file initially).  It builds a cache of compressed sections and membership tests should be quick.  I wonder if the speed issue is during the initial creation of segments or when actual read/seeks happen?  Definitely something to look into.

**Comment by NiklasBeierl** [comment]
Sorry I forgot to report back for a while. 
I found a workaround for people using `virsh dump`: You can use `virsh dump --memory-only` which produces an ELF type dump. These go through vol3 pretty fast. But maybe that is not an acceptable solution for everyone.

I also found another problem with the qemu layer: https://github.com/volatilityfoundation/volatility3/issues/587

**Comment by ikelos** [comment]
Thanks, have you tried #586?  It should be much much faster, but it needs some testing...
