### ISSUE TITLE
Use XDG_DATA_HOME instead of saving files to site-packages

### ISSUE THREAD

**Issue by ptrcnull** [volatilityfoundation/volatility3#598]
**Is your feature request related to a problem? Please describe.**
When Volatility is installed system-wide, plugins like `windows.info` don't work correctly, as they try to save files to a root-owned directory.

**Describe the solution you'd like**
Runtime files should be saved to user-writable locations, such as `$XDG_DATA_HOME`.

**Comment by ptrcnull** [comment]
Example logs:
```
vol -f memory.raw windows.info
Volatility 3 Framework 1.0.1
WARNING  volatility3.framework.symbols.windows.pdbutil: Cannot write necessary symbol file, please check permissions on /usr/lib/python3.9/site-packages/volatility3/symbols/windows/ntkrnlmp.pdb/3844DBB920174967BE7AA4A2C20430FA-2.json.xz
WARNING  volatility3.framework.symbols.windows.pdbutil: Cannot write necessary symbol file, please check permissions on /usr/lib/python3.9/site-packages/volatility3/framework/symbols/windows/ntkrnlmp.pdb/3844DBB920174967BE7AA4A2C20430FA-2.json.xz
WARNING  volatility3.framework.symbols.windows.pdbutil: Cannot write downloaded symbols, please add the appropriate symbols or add/modify a symbols directory that is writable
Progress:  100.00		PDB scanning finished                     
Unsatisfied requirement plugins.Info.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.nt_symbols']
```

**Comment by ikelos** [comment]
Thanks very much for filing the issue.  We store the profiles that we use within the directory structure of the volatility package, since we can't necessarily write them anywhere else but that directory will exist across every operating system.  Writing them on a per-user basis doesn't seem very useful for other users of the package (if the symbol tables are to be stored per-user, why not install the whole package in a user writable location, such as using a virtual environment), so it's unlikely we'll be changing the default operation of volatility unfortunately.  However, there is a way to modify the configuration of the default symbols directories, such that the new path should be used for writing the the symbols first.

By altering the [symbols_basepath constant](https://github.com/volatilityfoundation/volatility3/blob/581251cb0547b118ef01687aed81aab0a2f75f6d/volatility3/framework/constants/__init__.py#L23) you can put a user writable directory first, that would still be used by the installed system.  This can also done by adding `-s <path>` manually to each invocation of the CLI.

As such, I'm going to mark this issue as closed, but feel free to reopen the issue if you feel there's more discussion that needs to be had...  5:)
