### ISSUE TITLE
The python script name "vol.exe" conflicts with the Windows built-in command "vol"

### ISSUE THREAD

**Issue by 420313439** [volatilityfoundation/volatility3#621]
**Describe the bug**
The script name "vol.exe" conflicts with the Windows built-in command "vol", thus users can't just call "vol.exe" directly from elsewhere on Windows.

**Context**
Volatility Version:  2.0.0
Operating System:  Microsoft Windows 10 Pro
Python Version:  3.9.9
Command:  vol.exe 

**To Reproduce**

1. `pip install volatility3`
2. Use command "vol" within Windows cmd shell
3. built-in command "vol" is being called instead of the volatility, unless an absolute path provided

**Expected behavior**
volatility should be called correctly

**Screenshots**
![Screenshot 2022-01-14 112527](https://user-images.githubusercontent.com/16334986/149446575-b4d5be07-7af9-42f4-a372-c48f9ac09afb.png)

**Additional information**
None

**Comment by ikelos** [comment]
Thanks for pointing this out!  I've now tested this, and simply running `vol` does indeed launch the built-in windows command `vol` rather than running an executable in the current directory.  However, `.\vol` or `vol.exe` runs the executable rather than the built-in command.

Changing the name of the produced executable would make documentation more difficult (needing to specify the alternatives) and is not significantly different than adding `.\` at the beginning or `.exe` at the end.  I'm checking with the rest of the team as to how we'd like to resolve this, but I'm afraid it's likely just to be a documentation update...

**Comment by 420313439** [comment]
Thanks for responding! But i'm afraid that it wouldn't work if you are simply running `vol.exe` *out* of the directory of volatility... However, since you've noticed this issue, i am gonna close it for now. Thanks again.

**Comment by ikelos** [comment]
Ah, you're right, how strange?  It appears to be built into the shell itself, but it's strange that `vol.exe` works for local directories, but not when the directory is in the path?  5:S  I've found a workaround though, but that means it's less likely that we'll end up changing the executable name...  5:S

The workaround is to launch the executable with quotes around it, so:
```
C:\>"vol" ...
```
That works if `vol.exe` is in the path, and adding the quotes ignores any built-in commands (like vol).
