### ISSUE TITLE
Unsatisfied requirement plugins. Linux kernel Unable to validate the plugin requirements:

### ISSUE THREAD

**Issue by aryanadi-ic** [volatilityfoundation/volatility3#638]
Hi there! 

Please kindly help me with this, as I think there's something wrong with me or something missing when running the volatiltiy3 :

Unsatisfied requirement plugins. Linux kernel Unable to validate the plugin requirements:
Volatility Version:  3
Operating System:  Ubuntu 20.04.2 LTS (Mac OS Sierra 10.12 using Virtual Box)
Python Version:  3.8.10

Command:  

# /opt/volatility3/vol.py -f Linux_RAM.dd imageinfo
Volatility 3 Framework 2.0.0
usage: volatility [-h] [-c CONFIG] [--parallelism [{processes,threads,off}]] [-e EXTEND] [-p PLUGIN_DIRS] [-s SYMBOL_DIRS]
                  [-v] [-l LOG] [-o OUTPUT_DIR] [-q] [-r RENDERER] [-f FILE] [--write-config] [--clear-cache]
                  [--cache-path CACHE_PATH] [--offline] [--single-location SINGLE_LOCATION]
                  [--stackers [STACKERS [STACKERS ...]]]
                  [--single-swap-locations [SINGLE_SWAP_LOCATIONS [SINGLE_SWAP_LOCATIONS ...]]]
                  plugin ...
volatility: error: argument plugin: invalid choice imageinfo (choose from banners.Banners, configwriter.ConfigWriter, frameworkinfo.FrameworkInfo, isfinfo.IsfInfo, layerwriter.LayerWriter, linux.bash.Bash, linux.check_afinfo.Check_afinfo, linux.check_creds.Check_creds, linux.check_idt.Check_idt, linux.check_modules.Check_modules, linux.check_syscall.Check_syscall, linux.elfs.Elfs, linux.keyboard_notifiers.Keyboard_notifiers, linux.kmsg.Kmsg, linux.lsmod.Lsmod, linux.lsof.Lsof, linux.malfind.Malfind, linux.proc.Maps, linux.pslist.PsList, linux.pstree.PsTree, linux.tty_check.tty_check, mac.bash.Bash, mac.check_syscall.Check_syscall, mac.check_sysctl.Check_sysctl, mac.check_trap_table.Check_trap_table, mac.ifconfig.Ifconfig, mac.kauth_listeners.Kauth_listeners, mac.kauth_scopes.Kauth_scopes, mac.kevents.Kevents, mac.list_files.List_Files, mac.lsmod.Lsmod, mac.lsof.Lsof, mac.malfind.Malfind, mac.mount.Mount, mac.netstat.Netstat, mac.proc_maps.Maps, mac.psaux.Psaux, mac.pslist.PsList, mac.pstree.PsTree, mac.socket_filters.Socket_filters, mac.timers.Timers, mac.trustedbsd.Trustedbsd, mac.vfsevents.VFSevents, timeliner.Timeliner, windows.bigpools.BigPools, windows.cmdline.CmdLine, windows.crashinfo.Crashinfo, windows.dlllist.DllList, windows.driverirp.DriverIrp, windows.driverscan.DriverScan, windows.dumpfiles.DumpFiles, windows.envars.Envars, windows.filescan.FileScan, windows.getservicesids.GetServiceSIDs, windows.getsids.GetSIDs, windows.handles.Handles, windows.info.Info, windows.malfind.Malfind, windows.memmap.Memmap, windows.modscan.ModScan, windows.modules.Modules, windows.mutantscan.MutantScan, windows.poolscanner.PoolScanner, windows.privileges.Privs, windows.pslist.PsList, windows.psscan.PsScan, windows.pstree.PsTree, windows.registry.certificates.Certificates, windows.registry.hivelist.HiveList, windows.registry.hivescan.HiveScan, windows.registry.printkey.PrintKey, windows.registry.userassist.UserAssist, windows.ssdt.SSDT, windows.statistics.Statistics, windows.strings.Strings, windows.symlinkscan.SymlinkScan, windows.vadinfo.VadInfo, windows.virtmap.VirtMap)

# /opt/volatility3/vol.py -f Linux_RAM.dd linux.lsof.Lsof
Volatility 3 Framework 2.0.0
Progress:  100.00		Stacking attempts finished
Unsatisfied requirement plugins.Lsof.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.Lsof.kernel']

# /opt/volatility3/vol.py -f Linux_RAM.dd linux.lsmod.Lsmod 
Volatility 3 Framework 2.0.0
Progress:  100.00		Stacking attempts finished
Unsatisfied requirement plugins.Lsmod.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.Lsmod.kernel']

# /opt/volatility3/vol.py -f Linux_RAM.dd linux.malfind.Malfind
Volatility 3 Framework 2.0.0
Progress:  100.00		Stacking attempts finished
Unsatisfied requirement plugins.Malfind.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.Malfind.kernel']

# /opt/volatility3/vol.py -f Linux_RAM.dd linux.pslist.PsList
Volatility 3 Framework 2.0.0
Progress:  100.00		Stacking attempts finished
Unsatisfied requirement plugins.PsList.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.PsList.kernel']

# /opt/volatility3/vol.py -f Linux_RAM.dd linux.pstree.PsTree
Volatility 3 Framework 2.0.0
Progress:  100.00		Stacking attempts finished
Unsatisfied requirement plugins.PsTree.kernel: Linux kernel
Unable to validate the plugin requirements: ['plugins.PsTree.kernel']

I was trying to figure out what was occuring, what did I miss... but I hvn't got a clue yet. Please kindly help me. Thanks very much.

**Comment by ikelos** [comment]
Hi there,

I'm sorry the error messages aren't as clear as they could be.  The first one should be pretty clear:
```volatility: error: argument plugin: invalid choice imageinfo```
Imageinfo was the name of a plugin for volatility 2, but volatility 3 is a completely new program.  It has many similarities, but the names of plugins aren't exactly the same, so that's why that plugin didn't work.

All the others are saying that it can't find the linux kernel (and thus can't identify the image to do anything with it).  In volatility 2 you'd need a profile, in volatility 3 we require a little more information and it's not easily transferred between versions of the same operating system.  As such, you probably don't have the correct symbols files so you'll like have to go make them and then put then in the right location.  You should probably have a read through this section of the documentation: https://volatility3.readthedocs.io/en/latest/symbol-tables.html#mac-linux-symbol-tables

If you've got more questions, you'll probably get a more interactive response from our slack channel (https://www.volatilityfoundation.org/slack).  Since this isn't a bug in volatility I'm going to close it off, but please do come to the slack channel if you have any questions or problems like this, there's a lot of people that can help.  5:)
