### ISSUE TITLE
Null pointer dereference in UNICODE_STRING

### ISSUE THREAD

**Issue by paulkermann** [volatilityfoundation/volatility3#652]
Ran into an issue with `UNICODE_STRING`'s `get_string` function, when `self.Buffer` is null.
`self.Buffer.dereference()` fails, and `InvalidAddressException` gets thrown.

I'm aware of commit 00f3b4fb4448cd121d472effcaaf37f3e2a20375; I'd prefer at least a more specific error in this case, rather than a page fault error (which is intended for actual invalid addresses and paged out memory).

This occurrence (`UNICODE_STRING` with NULL buffer and 0 length) is not uncommon in Windows judging by my experience.

I think the function should return `""` if `self.Length` is zero. I'd be happy to implement this change if you'd like.

**Comment by ikelos** [comment]
Thanks, I'll bring it up in the next meeting, but as you point out we made an explicit decision to throw errors so users know that something went wrong.  We'll consider the corner case where length is 0, but we'll probably still throw an InvalidAddress exception where length is positive but the pointer can't be accessed, since that's in keeping with accessing a pointer that didn't go anywhere.  If you'd like we can also discuss an explicit exception for trying to access a pointer whose address is 0 (and page 0 isn't mapped)?

**Comment by paulkermann** [comment]
That's great, thanks.

> If you'd like we can also discuss an explicit exception for trying to access a pointer whose address is 0 (and page 0 isn't mapped)?

If the corner case is handled no explicit exception is needed.

**Comment by ikelos** [comment]
Yep, word is that's ressonable, so I'll get that coded up tonight.

**Comment by ikelos** [comment]
This actually changes the states that can come from trying to read a string.
Before:
```
Length >0, good pointer -> string
Length >0, bad pointer -> exception
Length=0, good pointer -> ''
Length=0, bad pointer -> exception
```
which has now changed to:
```
Length >0, good pointer -> string
Length >0, bad pointer -> exception
Length=0, good pointer -> ''
Length=0, bad pointer -> ''
```
There was only one corner case where we were relying on this distinction, and it was easy to fix up, but it will make it more difficult for users to determine when to return an AbsentValue rather than a empty string.  So far it's not high impact, but this may need revisiting if we get more reports of breakages in other users' plugins.
