### ISSUE TITLE
Question about the location of a specific netscan symbol file.

### ISSUE THREAD

**Issue by digitalisx** [volatilityfoundation/volatility3#691]
Hello, everyone in the community. 🙂

I checked the Symbol files and found that one of the Symbol files in netscan is in the top directory.
([netscan-win81-19935-x64.json](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/symbols/windows/netscan-win81-19935-x64.json))

As a result of tracking (#476) to see if this was intended,
I didn't see any other comments, and I think it was missing in the process of transferring Symbol JSON files to one folder.

I worked on the revised version of this in my folk repository.
I'm not sure, so I didn't open a PR.

May I know the intentions of this?
If this is a mistake, I will open PR immediately.

In addition, I would appreciate it if you could let me know if these questions are appropriate for the issue or if it is appropriate for Slack community to discuss.

**Comment by ikelos** [comment]
Thanks very much, that was a total oversight when I reviewed the PR!   Good catch, thanks!  I've made the changes to save you having to open up a PR...

Slack is probably a better first place to point stuff like that out, but if you don't get a quick reply and you think it might get forgotten then feel free to open an issue (particularly since it's a legitimate issue rather!)...  5:)

Thanks again!

**Comment by digitalisx** [comment]
Thank you for your prompt reply and action!
I will try to use Slack well. :)
