### ISSUE TITLE
_get_valid_table() dropping valid page tables

### ISSUE THREAD

**Issue by paulkermann** [volatilityfoundation/volatility3#723]
https://github.com/volatilityfoundation/volatility3/blob/8ac2b6ac8905149e5f77e0032dff21469edf3fbe/volatility3/framework/layers/intel.py#L176

Duplication of page table entries is not an indicator of an invalid page table.

I recently came across an instance where `read()` failed _even though the address was valid_, because of this condition (one table had all entries pointing to the same value).
This condition should be removed - that assertion isn't performed in actual address translation (in the CPU), and can make a researcher miss pages that exist and are actually valid.

**Comment by ikelos** [comment]
Hi there, you're right, we don't match exactly what processor does, but that's due to windows 10 introducing a complication where it will map very many pages, all of which point to the same place, without containing any useful data.  The best way we found to ensure we weren't endlessly scanning the same page over and over is to throw out a table if *every entry in the table maps to the same location*.  This means that if even one entry is different, the whole table will still be processed.  This seemed like the most suitable trade off, and we think is better than how volatility 2 handled the situation, throwing away the second page of any two consecutive pages that mapped to the same place.

We've yet to encounter a situation where those pages, even though valid, contained any useful data.  However, without this heuristic windows 10 virtual memory scans took orders of magnitude more time to complete.

So far you haven't made a good argument for drastically increasing the runtime of every windows plugin that scans a virtual space (including automagic) so as to not miss a page which has been mapped identically across an entire page table.  As such I'm going to mark this as closed.  If you have an example of pages that were missed even though they were valid, that were _in any way useful to your analysis of the image_ then feel free to reopen this and we'll consider adding it under a flag.  It's very unlikely that we'll remove this heuristic from the standard running, since at the moment there's no evidence that this isn't an extremely useful and valid means of reducing the amount of memory scanned.
