### ISSUE TITLE
MacOS Profile: macOS Monterey

### ISSUE THREAD

**Issue by bellohai** [volatilityfoundation/volatility3#747]
Hi, Did volatility support **MacOS Monterey version 12.0.1** profile?
I am having issue with "Unable to find an OS X profile for the given memory sample.

<img width="375" alt="macprofile" src="https://user-images.githubusercontent.com/49047882/170625494-076a3d85-275e-4fae-b4cf-b4bcb3b3fd3f.png">

**Comment by digitalisx** [comment]
Hello @GordonChaiCheenShun,
You used is `Volatility`, it may not be right to discuss this in the `Volatility3` repository.. :)
But to think about the solution, `Volatility3` uses **Symbol Tables** instead of the concept of **Profile**, tools such as `dwarf2json` will allow you to create and analyze **Symbol Tables** for your desired operating system (Linux or Mac).

**Comment by digitalisx** [comment]
Additional, It is not recommended to raise the same issue with many repositories unless you need it. Not only does it not guarantee a quick answer, but it can also confuse the maintainer. Before you raise an issue, consider what repositories are appropriate for the issues you face.. :)
(https://github.com/volatilityfoundation/volatility/issues/820, https://github.com/volatilityfoundation/profiles/issues/89)

**Comment by ikelos** [comment]
Volatility 3 would support it, but I don't know if it's the default set of system tables, or whether it's too recent.  If it's too recent, you can examine the files [here](https://github.com/volatilityfoundation/volatility3/tree/develop/development/mac-kdk) or use dwarf2json directly to generate your own profile, based on the [documentation](https://volatility3.readthedocs.io/en/latest/symbol-tables.html#mac-linux-symbol-tables) for making symbol tables.  As @digitalisx pointed out, the tables generated would *not* run under volatility 2.6, and I believe support for vol 2.6 was due to end in August to 2021 so it might be hopeful to think it will one day support more recent mac kernels.

I hope this helps, you can get more interactive support by asking questions on [our slack channel](https://www.volatilityfoundation.org/slack) (for both vol 2 and vol 3).  As such I'm going to close this issue (since it's open in two more appropriate places), but feel free to reopen it if you feel there's more to add to the discussion.  5:)
