### ISSUE TITLE
Unable to validate the plugin requirements: ['plugins.Crashinfo.primary']

### ISSUE THREAD

**Issue by Randark-JMT** [volatilityfoundation/volatility3#757]
**Describe the bug**
I was going to use Volatility to analyze the Windows memory dump file, but an error occurred

**Context**
Volatility Version:  Volatility 3 Framework 2.0.1
Operating System:  Windows
Python Version:  3.10.2
Command:  vol -vvv -f .\1.dmp windows.crashinfo 
![图片](https://user-images.githubusercontent.com/56223739/171016485-b56e4e22-761f-4866-9dff-964cfba0fea6.png)

**Comment by ikelos** [comment]
The error message is fairly clear, it seems volatility doesn't think the file D:\Downloads\funny.data exists?  Is the D: drive a mapped UNC path or some other strange drive?

**Comment by Randark-JMT** [comment]
@ikelos Sorry, I uploaded the wrong screenshot, I have fixed it now

**Comment by ikelos** [comment]
Ok, that says it only loaded the file layer and couldn't identify a crashdump layer beneath it, we don't seem to output enough information to identify why, but my guess would be that the header doesn't match.  At the moment we only support full crashdumps (types 1 and 5 if I recall correctly).  There is a pull request (#656)  to add more, but volatility isn't setup to handle partial crashdumps so that one's parked at the moment.

**Comment by Randark-JMT** [comment]
Ok, got it, thanks for your reply.

**Comment by ikelos** [comment]
No problem, I'm going to mark this as closed, but feel free to follow up if you discover the issue and/or reopen it if you need more support.  5:)
