### ISSUE TITLE
Dumping LSASS/Extracking domain hashes

### ISSUE THREAD

**Issue by Lvenizerv** [volatilityfoundation/volatility3#859]
Hi there,
I'm quite new to this, I've searched up a few tutorials on how to get this working and I've managed to dump the local pc hashes (administrator account, bla bla) using the hashdump plugin

I can't seem to dump the hashes of domain-joined users who remoted into the machine. How can I obtain hashes for them?
Also, I tried dumping the lsass process through pslit but it seems the lsass file was corrupted, any clue why?

Thanks in advance!

**Comment by ikelos** [comment]
Hi there, I'm afraid that's a little outside of the scope of this bug tracker.  This is for problems arising with the volatility 3 tool and its plugins.  If you'd like support in the tasks necessary to acquire the data you want to pass to the plugins, then you could try on the (volatility slack channels)[https://www.volatilityfoundation.org/slack], but otherwise there should be resources on the internet for doing this.  I'm going to mark this as closed, but if you have a specific issue in the volatility tool or find that a plugin does not work for some reason, then feel to reopen this...
