### ISSUE TITLE
Provide uninstall/remove command in setup.py

### ISSUE THREAD

**Issue by Hephaestus14089** [volatilityfoundation/volatility3#890]
It would be great to have an option to remove the package linked to the script used to build and install it.
Once its done, the README.md file can be updated to inform a user how to uninstall the program too.

**Comment by ikelos** [comment]
Volatility 3 is packaged using standard setuptools.  If they were installed using pip they can be removed using `pip uninstall`.  If you're just using `setup.py`, then you'll need to pass the `--record <filename>` option to create a list of all the files installed, and then remove those.  There's a number of supporting documents on the internet and due to using the standard tools for packaging python programs, I wouldn't class this as a bug in volatility.

Please feel free to reopen this if you think there's something significant change required by the volatility package to accommodate uninstallation, but it's packaged the same way the majority of python package on the internet are distributed and deviating from the norm is unlikely to be high priority.
