### ISSUE TITLE
Name error in the ARC4 of pycrypto module

### ISSUE THREAD

**Issue by Ananthavijay** [volatilityfoundation/volatility3#893]
**Describe the bug**
Name error in the ARC4 of pycrypto module

**Context**
Volatility Version:  3
Operating System:  Kali Linux
Python Version:  3.10.8
Suspected Operating System:  Kali Linux
Command:  vol

**To Reproduce**
Run any volatility command

1. Use command 'vol'
2. See error

**Expected behavior**
No error and it should display the volatility usage

![image](https://user-images.githubusercontent.com/35162705/210097263-d43b5aa9-0551-4fcb-807f-4f6fa1c7504d.png)

**Additional information**
- Installed volatility following this blog: https://seanthegeek.net/1172/how-to-install-volatility-2-and-volatility-3-on-debian-ubuntu-or-kali-linux/
- I am not sure If I am the only one getting this error
- This can be fixed by editing the `Crypto/Cipher/ARC4.py` in pycrypto module, changing **"xrange"** to **"range"**

**Comment by ikelos** [comment]
Hi, this is because pycrypto got forked and only the newer one is now updated.  The old one can be installed and used as if it provided pycrypto, but it contains code that is [not compatible with python 3](https://github.com/pycrypto/pycrypto/issues/327) due to the removal of automatic 2-to-3 conversion in more recent versions of setuptools.  The github repository has [been archived](https://github.com/pycrypto/pycrypto) and it should no longer be used.

The forked version is called `pycryptodome`, which was itself forked as `pycryptodomex` and, in fact, it is `pycryptodome` that is listed in the requirements.txt.  It is very difficult for us to resolve issues in dependencies that all provide the same package name, but please try removing any other packages and install only either `pycryptodome` or `pycryptodomex`.

The blog article you mentioned, posted in 2021 unfortunately provides advice that is no longer applicable or suitable.  Volatility 3 can be installed like any other modern python package and comes with complete `requirements.txt` files, or can even be installed directly using `pip install volatility3`.

I'm going to close this issue off, but if you discover that you have only `pycryptodome` or `pycryptodomex` installed and are still experiencing the problem, please feel free to reopen this issue.
