### ISSUE TITLE
Maple Trees Replaced MMap - Broken v6.1

### ISSUE THREAD

**Issue by sempervictus** [volatilityfoundation/volatility3#909]
**Describe the bug**
```python
Traceback (most recent call last):
  File "/home/rage/Code/Python/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/tmp/volatility3/volatility3/cli/__init__.py", line 797, in main
    CommandLine().run()
  File "/tmp/volatility3/volatility3/cli/__init__.py", line 445, in run
    renderers[args.renderer]().render(constructed.run())
  File "/tmp/volatility3/volatility3/cli/text_renderer.py", line 193, in render
    grid.populate(visitor, outfd)
  File "/tmp/volatility3/volatility3/framework/renderers/__init__.py", line 241, in populate
    for level, item in self._generator:
  File "/tmp/volatility-gpg/linux/gpg_full.py", line 188, in _generator
    for offset, passphrase, secret_size, plaintext in self.locate_timestamps(self.context, tasks):
  File "/tmp/volatility-gpg/linux/gpg_full.py", line 98, in locate_timestamps
    memory_sections = list(task.get_process_memory_sections(heap_only=False))
  File "/tmp/volatility3/volatility3/framework/symbols/linux/extensions/__init__.py", line 221, in get_process_memory_sections
    for vma in self.mm.get_mmap_iter():
  File "/tmp/volatility3/volatility3/framework/symbols/linux/extensions/__init__.py", line 302, in get_mmap_iter
    if not self.mmap:
  File "/tmp/volatility3/volatility3/framework/objects/__init__.py", line 968, in __getattr__
    raise AttributeError(
AttributeError: StructType has no attribute: symbol_table_name1!mm_struct.mmap
```
^^ its hard to get an mmap iterator when there is no mmap struct member in-play.
```c
struct [mm_struct](https://elixir.bootlin.com/linux/v5.19.17/C/ident/mm_struct) {
	struct {
		struct [vm_area_struct](https://elixir.bootlin.com/linux/v5.19.17/C/ident/vm_area_struct) *[mmap](https://elixir.bootlin.com/linux/v5.19.17/C/ident/mmap);		/* list of VMAs */
```
became
```c
struct [mm_struct](https://elixir.bootlin.com/linux/latest/C/ident/mm_struct) {
	struct {
		struct [maple_tree](https://elixir.bootlin.com/linux/latest/C/ident/maple_tree) [mm_mt](https://elixir.bootlin.com/linux/latest/C/ident/mm_mt);
```
Seems that `get_process_memory_sections` will need to parse the new structures to work.

**Context**
Volatility Version:  git master
Operating System:  Arch
Python Version:  3.10.9
Suspected Operating System:  
Command:  

**To Reproduce**

1. try to `get_process_memory_sections` from a 6.1.11 memory image

**Comment by sempervictus** [comment]
Digging into this a bit, it seems non-trivial since the linear list of VMAs is replaced with a tree which has its own iterator, macro, and ordering logic. Hoping someone with a bit more experience with the new `mm_struct` and how Volatility works might weigh in with a suggestion or remedial approach.

**Comment by ikelos** [comment]
Sounds like a job for super @atcuno ! 5;P

**Comment by eve-mem** [comment]
Hello @sempervictus - I've been looking into this and have something that I think is almost working (64 bit only, not tested 32 bit yet).

Is it possible for you to share your mem dump and symbols for me to test on? I've been working on a version of the kernel I set up myself, it would be nice to compare to something in the wild. 

Here is some information on the structure itself if it's helpful... (and I am very happy to be corrected on anything below if I have made a mistake!)

In short, mm_struct now has mm_mt for memory mappings. It is a maple tree and replaces the linked list and rbtree. 

The Maple Tree structure itself is simple. A pointer to a lock, a pointer to the root node, and some flags. The flags can tell you how deep the tree is, which is useful to know. 

The pointer to the root node actually encodes extra information and is not directly a pointer, the maple tree does this a lot! It encodes the type of node as well so you need to mask this off before following the pointer. (It's explained well here: https://elixir.bootlin.com/linux/latest/source/include/linux/maple_tree.h#L254)

For the root node the first 8 bytes are a pointer back to the maple tree struct itself, however it has bit 0 set to show that it is a root node. This is useful as it lets you verify that you are following the pointers correctly. In non-root nodes this pointer goes to the parent node and does not have bit 0 set.

Nodes can be 1 of 4 types. Each storing different amounts of information. The main thing we're interested in is the 'slots' as these either contain pointers to other nodes in the tree or actual pointers to the VMA we are after. Care has to be taken when following the pointers to nodes to mask off the lower 8 bits as they're used to encode the node type. 

It would be possible for us to follow the pivots in the nodes to jump quickly to the VMA of interest given a particular address, but I'm focusing on making an iterator to return all the VMAs for a mm_struct specifically rather than generically handling maple trees (although I think they will pop up in other places in the kernel so it'll be a good idea to start adding that support into vol!)

It's actually a really clever structure making squeezing out lots of information into a small structure.

**Comment by sempervictus** [comment]
@eve-mem: thanks for the detailed writeup. Unfortunately i don't have _that_ dataset available anymore, nor would i be able to share it as its unsanitized, but i may be able to produce another one if need-be. Its a very very rare day for me to set up a vanilla build - we're a grsec shop and customer-facing kernels are built off linux-hardened (with lkrg and some other stuff in 'em which can confuse vol).
If you have any debug kernel to test from a distro, `avml` should suffice for capture and it doesn't use a kmod like `lime`.
