### ISSUE TITLE
The support for true crypt is needed

### ISSUE THREAD

**Issue by SSRemex** [volatilityfoundation/volatility3#925]
Is vol3 supporting for true crypt now?
I can't find a plugin to process true crypt when using vol3.

**Comment by ikelos** [comment]
Support for truecrypt hasn't yet been implemented for volatility 3, but the use of truecrypt has also diminished since it stopped being developed in 2014.  If someone's willing to devote some time to implementing support for it (or porting the volatility 2 plugin), we'll be happy to consider it for inclusion, but it's not a priority for the small volunteer development team to add to the main codebase.

Issue #259 is still open, and as such I'll be closing this and recommend joining that issue, so that we can keep everything in one place.
