### ISSUE TITLE
Syntax for --single-swap-locations is confusing/inconsistent with other options

### ISSUE THREAD

**Issue by iMHLv2** [volatilityfoundation/volatility3#937]
**Describe the bug**
The syntax for using `--single-swap-locations` is confusing/inconsistent with other options. For example, for the main file, all of the following are valid:

* `--single-location mem.dump`
* `--single-location=mem.dump`
* `-f mem.dump` 

However, for swap files, only `--single-swap-locations=pagefile.sys` works. Using a space between the option and argument results in the following:

```
$ vol3 -f hiberfil.raw --single-swap-locations pagefile.sys windows.pslist    
Volatility 3 Framework 2.4.2
usage: volatility [-h] [-c CONFIG] [--parallelism [{processes,threads,off}]] [-e EXTEND] [-p PLUGIN_DIRS] [-s SYMBOL_DIRS] [-v] [-l LOG] [-o OUTPUT_DIR]
                  [-q] [-r RENDERER] [-f FILE] [--write-config] [--save-config SAVE_CONFIG] [--clear-cache] [--cache-path CACHE_PATH] [--offline]
                  [--single-location SINGLE_LOCATION] [--stackers [STACKERS ...]] [--single-swap-locations [SINGLE_SWAP_LOCATIONS ...]]
                  plugin ...
volatility: error: Please select a plugin to run
```

**Context**
Volatility Version:  develop branch, commit ebb74e2f9292b7cdd211c4886b06fb407e751c80
Operating System:  Kali Linux 2023.1
Python Version:  3.11.2
Suspected Operating System:  Windows
Command:  see above

**Comment by ikelos** [comment]
Having investigated this I've made improvements to alerting the user when the location of a swap file isn't found (although execution will continue).  As to the option parsing, this is in keeping with normal argparse behaviour.  If the argument is used before another argument, spaces can be used to delimit it, but immediately before a parameter without `--` (such as plugin), it must be specified with `--param=item1,item2`.

For clarity:
```
vol3 --single-swap-locations pagefile.sys -f hiberfil.raw  windows.pslist
```
should work just fine, but because the parser can't determine whether `windows.pslist` is a plugin or a filename for `--single-swap-locations`, then it requires the use of comma separators and `=` directly after the flag.  This is normal argparse behaviour and is unlikely to be fixed.

I have, however, improved the support for normal files rather than URIs, and implemented a warning when a location URI cannot be found.
