### ISSUE TITLE
Unable to validate the plugin requirements

### ISSUE THREAD

**Issue by aleff-github** [volatilityfoundation/volatility3#943]
Hello dear,
- I have cloned the volatility3 from origin/develop branch
- then, i have sent the `pip install -r requirements.txt`
- then, `python3 setup.py build`
- then, `python3 setup.py install`
- then, `pip install -r requirements.txt`
- then, `python .\vol.py -f C:\Users\User\memory-dump\mem.elf windows.info` knowing that the image have the following features:

```
Suggested Profile(s) : Win7SP1x64, Win7SP0x64, Win2008R2SP0x64, Win2008R2SP1x64_23418, Win2008R2SP1x64, Win7SP1x64_23418
AS Layer1 : WindowsAMD64PagedMemory (Kernel AS)
AS Layer2 : VirtualBoxCoreDumpElf64 (Unnamed AS)
AS Layer3 : FileAddressSpace (/home/user/dumps/mem_dumps/01/mem.elf)
```

and I receive this error message:
```
Volatility 3 Framework 2.4.2
Progress:  100.00               PDB scanning finished
Unsatisfied requirement plugins.Info.kernel.layer_name:
Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The file is a valid memory image and was acquired cleanly

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.layer_name', 'plugins.Info.kernel.symbol_table_name']
```

**Comment by ikelos** [comment]
Hi Aleff,

Thanks very much for the information, but to help us debug this further, please could you include the output from running the same command but using `python ./vol.py -vvv` at the beginning please?

It's possible that we don't yet support the virtualbox core format.  You could test whether this is the case by using volatility 2 to dump that image to a raw format and then try analyzing that with volatility 3.

With the debug output from `-vvv` we can investigate this further and figure out what's going on... 5:)

**Comment by aleff-github** [comment]
> Hi Aleff,
> 
> Thanks very much for the information, but to help us debug this further, please could you include the output from running the same command but using `python ./vol.py -vvv` at the beginning please?
> 
> It's possible that we don't yet support the virtualbox core format. You could test whether this is the case by using volatility 2 to dump that image to a raw format and then try analyzing that with volatility 3.
> 
> With the debug output from `-vvv` we can investigate this further and figure out what's going on... 5:)

Now i moved the dump into the same folder of vol.py and i runned the command `python .\vol.py -vvv -f .\dump.elf windows.info`

the output is:
```
Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']
```

**Comment by aleff-github** [comment]
@ikelos I did exactly the same operations in a Debian VBox and it works now with the same dump, have a nice debug :)

**Comment by ikelos** [comment]
I'm glad you got it resolved, you didn't include the complete output from the dash `-vvv` run, so there's no information for us to debug, you should've had a significant number of log messages to help us determine what was happening internally.  Changing the folder that the file was in should not have altered the error message you received, but again without debugging information it's hard to tell what's going on.

With the new image, I'm glad that it was able to find the appropriate symbols.  Each linux-based operating system will need symbols constructing for it individually using dwarf2json, the linux.zip file provided contains a very small number of example debian kernel symbols. simply because of the large number of linux kernel configurations that would need to be covered.

If you'd like us to investigate the file location issue between your first and second runs, please feel free to reopen this and provide the complete additional information requested...  5:)
