### ISSUE TITLE
Please make a 3.x release

### ISSUE THREAD

**Issue by rhertzog** [volatilityfoundation/volatility3#95]
volatility 2.6 is packaged in Debian and we will want to upgrade our users to the latest upstream release now available in volatility3.git... but for this we need you to continue to increase the version number.

So please release volatility3 as a 3.x version number and don't use volatility3 version 1.0.0. It's just confusing....

Thank you in advance, a Debian & Kali packager.

**Comment by ikelos** [comment]
Hiya, I'm sorry it's confusing, but the new package is called volatility3, not volatility, and we'd encourage package maintainers to keep that naming convention.

We've decided to adopt the Semantic Versioning scheme for this package's version numbers, and trying never to increase the major version number would be an impossible task.  Rather than producing volatility 4, 5, 6, etc when we have to change the API, we felt it would be much less confusing for users to call the package volatility3 and start the numbering of volatility3 from version 1.

I hope you find a solution that doesn't cause you too many difficulties in packaging.  Please feel free to reopen this if you have strong views to the contrary, but there would need to be better reasoning than the points I just made to consider changing our strategy...

**Comment by rhertzog** [comment]
FWIW I'm not asking you to not increase the major version, starting at 3.0.0 and going to 4.x and 5.x later is fine from my point of view.

You changed the name of the git repository but the name of the Python library is unchanged and you likely want to have consistency... so that https://pypi.org/project/volatility/ has the latest version instead of having to use https://pypi.org/project/volatility3/ installing something called "volatility" without the 3 suffix.

For me the whole rename was not really required because the old version has no future and you the Python 3 version should just replace the former version, but it's your choice to rebrand it. But package maintainers would like users to upgrade from one to the other without problems and the binary packages are often named after the name of the Python library shipped (not after the name of the git repository). We can always find work-arounds but they only add confusion, hence my suggestion to get to a clean situation at the upstream level.
