### ISSUE TITLE
Command syntax for running community-made plugins

### ISSUE THREAD

**Issue by infinitebugs32** [volatilityfoundation/volatility3#959]
Hi,

So from what I've understood, the custom plugins are `.py` files that go into a file that is specified through the `-p` argument of `vol.py` but I can't manage to make it work:

I am trying to run [this](https://github.com/forensicxlab/volatility3_plugins/blob/main/prefetch.py) plugin ([more info](https://www.forensicxlab.com/posts/prefetch/)).

I have tried the followings:
`python3 vol.py -p plugins/ -f file.raw prefetch`
`python3 vol.py -p volatility3/plugins/ -f file.raw prefetch`

I am running the command from the root of `volatility3/` folder and the `prefetch.py` file is in `volatility3/volatility3/plugins`

Thank you for your help

**Comment by ikelos** [comment]
Hiya, very close, but it isn't just a `.py` file.  All `.py` files are imported, and any class within them that inherits from [PluginInterface](https://github.com/volatilityfoundation/volatility3/blob/8e56cb39d13c22575ba5133ffbc6b83344bed0ba/volatility3/framework/interfaces/plugins.py#L87) will get picked up.  It's easy to check whether it has been picked up or not, because it should be listed under `--help`.

The `plugins` and `framework/plugins` folders are always imported, so just dropping the file in there should be enough, you can use `-p` if you want to keep it in a different folder.  If the file doesn't import for some reason, you can see exactly why by running `vol.py -vv` to see the warnings and error, but again, at least `vol.py --help` should tell you that it couldn't be imported for some reason.

Please check that you have a class that inherits from the `PluginInterface` (and implements at least the `run` method) and let us know if you're still having difficulties to so we can either investigate further or close off this request...  5:)

You might also find additional useful information at https://volatility3.readthedocs.io/en/latest/simple-plugin.html#how-to-write-a-simple-plugin

**Comment by ikelos** [comment]
Have you made any progress on this?  Without seeing the code you're trying to load in `prefetch.py` it's difficult to know what the problem is?
