### ISSUE TITLE
Translate a physical address to a virtual address ?

### ISSUE THREAD

**Issue by yarona1993** [volatilityfoundation/volatility3#979]
Is there are way to translate a physical address to a virtual address ?

**Comment by ikelos** [comment]
Hi there, I'm afraid there's no simple way, because the mapping between physical and virtual doesn't have to be 1-1.  You could easily have a physical address that is mapped into multiple different virtual address (for example, memory shared across processes), or that isn't mapped in at all (but still contains previous data that had been mapped in).

You could go through and build a big table to all the mappings from virtual addresses to physical addresses and then reverse it, and that is pretty much how the strings plugin works (taking string offsets in the physical file and mapping them to potentially multiple virtual addresses), but it takes a very long time to [build the initial table](https://github.com/volatilityfoundation/volatility3/blob/6c0ce1d130092ac496c85eec294580a689c6ce2d/volatility3/framework/plugins/windows/strings.py#L122) and as I say, it won't necessarily give you a single answer.  At the moment it's windows specific because it understands the list of processes, and so can build the reverse map for every process.  That capbility hasn't been implemented for linux yet, but there's no reason it couldn't.  I hope that helps?

Since this isn't a bug in volatility, I'll mark it as closed.  If you have further questions, please use our [slack channels](https://www.volatilityfoundation.org/slack) where the whole community will see and be able to help provide answers.  Thanks...

**Comment by eve-mem** [comment]
Hey @yarona1993 - if it helps here is a worked example. 

Lets pretend we are working on a linux memory dump in volshell.

```
python volshell.py -f .\linux-sample-1.dmp -l
Volshell (Volatility 3 Framework) 2.4.2
Progress:  100.00               Stacking attempts finished
    Call help() to see available functions

    Volshell mode        : Linux
    Current Layer        : layer_name
    Current Symbol Table : symbol_table_name1
    Current Kernel Name  : kernel
```

Now lets say while exploring we find this section of memory. We spot 0xffffffff814052a0 and we know it's a pointer to a virtual address we'd like to translate it to a physical one. 

```
(layer_name) >>> dq(149534111516480)
0x88001f994740    0000000000000001 ffff88001f998000    ........ ........
0x88001f994750    0040210000000002 0000000000000000    .@!..... ........
0x88001f994760    0000000000000000 0000000000000000    ........ ........
0x88001f994770    0000007800000078 0000000000000078    ...x...x .......x
0x88001f994780    ffffffff814052a0 0000000000000400    .....@R. ........  <--- Here is that pointer!
0x88001f994790    0000000000400000 0000000000000001    .....@.. ........
0x88001f9947a0    0000000000000000 0000000000000000    ........ ........
0x88001f9947b0    ffff88001f9947b0 ffff88001f9947b0    ......G. ......G.
```

We can use volatility to translate it for us. In this example it translates to a physical address of 20992672. That's great, now we have done the translation. 
```
(layer_name) >>> self.context.layers['layer_name'].translate(0xffffffff814052a0)
(20992672, 'memory_layer')
```

However that only worked because it was a virtual address for the kernel, if we attempt to translate something smaller we'll hit an error. Here we try to translate 0x608038 but it fails. 

```
(layer_name) >>> self.context.layers['layer_name'].translate(0x608038)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\eve\volatility3\volatility3\framework\layers\linear.py", line 20, in translate
    mapping = list(self.mapping(offset, 0, ignore_errors))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eve\volatility3\volatility3\framework\layers\intel.py", line 274, in mapping
    for offset, size, mapped_offset, mapped_size, map_layer in self._mapping(
  File "C:\Users\eve\volatility3\volatility3\framework\layers\intel.py", line 317, in _mapping
    mapped_offset, _, layer_name = self._translate(offset)
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eve\volatility3\volatility3\framework\layers\intel.py", line 138, in _translate
    entry, position = self._translate_entry(offset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eve\volatility3\volatility3\framework\layers\intel.py", line 179, in _translate_entry
    raise exceptions.PagedInvalidAddressException(
volatility3.framework.exceptions.PagedInvalidAddressException: Page Fault at entry 0x0 in table page directory pointer
```

It fails because we need to tell volatility which process to work from, the same virtual address can point to many different physical addresses, so the context is key. 

Here we change to pid 1, and then use translate again but on the layer that is specific to this process. This time it works, and we find that it translates to 497668152 physically. 

```
(layer_name) >>> ct(1)
(layer_name_Process1) >>> self.context.layers['layer_name_Process1'].translate(0x608038)
(497668152, 'memory_layer')
```

If we change to another process and try again, it fails again. That's because in the context of this process that address means nothing! 

```
(layer_name_Process1) >>> ct(8471)
(layer_name_Process8471) >>> self.context.layers['layer_name_Process8471'].translate(0x608038)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\eve\volatility3\volatility3\framework\layers\linear.py", line 20, in translate
    mapping = list(self.mapping(offset, 0, ignore_errors))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eve\volatility3\volatility3\framework\layers\intel.py", line 274, in mapping
    for offset, size, mapped_offset, mapped_size, map_layer in self._mapping(
  File "C:\Users\eve\volatility3\volatility3\framework\layers\intel.py", line 317, in _mapping
    mapped_offset, _, layer_name = self._translate(offset)
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eve\volatility3\volatility3\framework\layers\intel.py", line 142, in _translate
    raise exceptions.PagedInvalidAddressException(
volatility3.framework.exceptions.PagedInvalidAddressException: Page Fault at entry 0x0 in page entry
```

However if we try to translate that original kernel address on any of the processes it will be translated, and they are all the same. That's because each process has the same view of kernel memory. 

```
(layer_name) >>> self.context.layers['layer_name_Process1'].translate(0xffffffff814052a0)
(20992672, 'memory_layer')
(layer_name) >>> self.context.layers['layer_name_Process8471'].translate(0xffffffff814052a0)
(20992672, 'memory_layer')
```

I hope that makes some sense and explains why translating isn't as straight forward as it might seem but it's also not too difficult if you know the context of the address you are trying to translate. 

@ikelos did recently add some docs on this that you might find helpful - https://volatility3.readthedocs.io/en/latest/basics.html#worked-example

Hope that helps!

(Edit: it gets more complex if the memory dump isn't raw file - but I didn't want to over complicate it)
