### ISSUE TITLE
Redline Memory Image Support

### ISSUE THREAD

**Issue by TheHmadQureshi** [volatilityfoundation/volatility3#98]
Hello,

I created a memory image using redline(memoryze) and it created a .dat file for memory acquisition. I was wondering if there's any way analyze that memory dump using volatility? 

Appreciate your help.

Thanks

**Comment by ikelos** [comment]
I believe redline's `.dat` files are just raw memory images, and should therefore work with volatility 3.  Have you tried it, and if so what results did you have?

**Comment by TheHmadQureshi** [comment]
Thanks for replying @ikelos. I got this output:

![1](https://user-images.githubusercontent.com/9057459/67167030-9f101080-f3ae-11e9-84e7-aab722fc7a7e.PNG)

I made sure that symbols are in the right directory and in order. i am not sure why its not working.

**Comment by ikelos** [comment]
Hmmm, so first off, from the output, it looks like the raw memory image is fine (and that the dat files that Redline/Memoryze produces are just raw memory images), and it did find an intel layer (because you didn't get an issue about primary not being fulfilled, just the nt_symbols).

You can run the command again using `vol.py -vvv` rather than `vol.py` and see if it identifies a windows kernel to use, and then verify whether it found such a symbol table or not.  It's possible the memory image was smeared or doesn't have enough information to be able to load the necessary windows information in it.  Let me know what the output of `vol.py -vvv` shows and we can go from there...  5:)

**Comment by ikelos** [comment]
Hiya, Thanks for running that!  As it turns out, the TypeError is fine and expected, the issue is when the pdbscan automagic tries to determine the kernel base value.  At the moment, it tries three different methods, and the third one finds a potential kernel base, but then fails to read that page of memory.

This is actually the same type of trace as seen by @araaj in issue #96.  As I said there, my best guess is that the acquisition wasn't successful.  If you could produce a memory image that you're happy to make public, then we could try to diagnose the issue further?  More than that, I'm not sure how best to help.

Again, it looks as though the .dat file is a normal memory image and can be read ok by volatility when it's intact.  I'd need to check a failing file to find out if the layout of the file is different, or there's an issue in vol3 that causes the problem...

**Comment by ikelos** [comment]
So, just to note, I believe the redline `.dat` format is supported by volatility and there's been no further comments in two weeks, so I'm going to mark this as closed.  Feel free to reopen it if you feel the issue is still present...  5:)
