### ISSUE TITLE
volatility -h give error line 118     print "\n"     ^^^^^^^^^^

### ISSUE THREAD

**Issue by Shivam-Kumar-1** [volatilityfoundation/volatility3#980]
**Describe the bug**

**Context**
Volatility Version:  3
Operating System:  kali linux
Python Version:  3
Suspected Operating System:  
Command:  

**To Reproduce**

1. Use command '...' volatility -h
2. See error 
File "/usr/bin/volatility", line 118
    print "\n"
    ^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Expected behavior**

**Example output**
Please copy and paste the text demonstrating the issue, ideally with verbose output turned on (`vol.py -vvv ...`).  

Text is preferred to screenshots for searching and to talk about specific parts of the output.

**Additional information**
Add any other information about the problem here.

**Comment by eve-mem** [comment]
Hi @5h1v4m-0 - I've not been able to recreate this with a current version of Volatility 3. 

Am I correct in thinking you are trying to use the version that is bundled with kali? If so which version of kali are you using? 

The error message you have makes me think that it's actually Volatility 2 that is bundled in.

**Comment by ikelos** [comment]
I suspect @eve-mem is correct, as you can see from [the repo](https://github.com/volatilityfoundation/volatility3/blob/develop/vol.py) the main volatility python script doesn't have any print statements in it whereas you can see that volatility 2 (which only runs under python 2) has a [print statement on line 118](https://github.com/volatilityfoundation/volatility/blob/master/vol.py#L118), as your error message indicates.  You should be able to use the python2 interpreter to run this old version of volatility, although please be aware that this version of volatility *and* python 2 have both reached their respective end-of-life dates.  Please consider installing volatility 3 (`pip install volatility3`) and see if that can handle your memory forensic needs?

Since this isn't a volatility 3 issue, I'm going to close this off.  Please feel free to reopen it if you feels there's something more we can do concerning it.
