### ISSUE TITLE
Uneducated idea : run the memory image with qemu to query the kernel

### ISSUE THREAD

**Issue by 59e5aaf4** [volatilityfoundation/volatility3#983]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when waiting for volatility to produce output since scanning large memory images takes time. I had a thought that when un-pausing a frozen vm in a random hypervisor, the kernel is up in seconds, and able to figure out offsets to processes, etc. So I had an idea that most likely is 100% non-realistic, I'm definitely not well versed in kernel dark arts, or booting OSes in general.

Question : would it make sense to boot the RAM image, and then use kernel API calls to interrogate the OS about processes, etc ?

**Describe the solution you'd like**
A completely crazy system that snapshots the memory image, boots a copy in a disk-less mode, and uses hypervisor tricks to call functions that would provide offsets to things we need to know, then feeding back to volatility these offsets for faster operations.

I'm not even sure this provides any useful info, given that you'd most likely need to figure out some kernel offset to point the CPU at when booting back, you can't just throw memory at a CPU. 

Also, there would be major issues related to the absence of any device probably alarming the kernel pretty quickly that something is wrong.

**Describe alternatives you've considered**
Sticking to the pure static analysis even if it takes time, like a reasonable citizen.

**Additional information**

Some links related to the "restore" feature of libvirt :
* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-save-config#sect-Starting_suspending_resuming_saving_and_restoring_a_guest_virtual_machine-Save_a_guest_virtual_machine
* https://github.com/juergh/lqs2mem.py converting the LQS format to a raw memory image
* https://unix.stackexchange.com/questions/121907/what-is-the-structure-of-libvirt-qemu-vm-dump-save-files said format is rather mysterious
* virtualbox has the "savestate" command generating such a mem snapshot ( .vmdk diff for the disk, and .sav for the memory ) https://parsiya.net/blog/2018-01-29-virtualbox-live-state-file-format/ 

Feel free to close as completely nonsensical. I just wanted to throw this idea at you folks.

**Comment by ikelos** [comment]
So, it's a really interesting idea!  It might very well be possible to do, and all the architectures that volatility handles should spin up.  Some difficulties you might run into are:

* Hardware differences
  The VM might not spin up correctly, or the lack of a hard disk might cause a very early process/handles on files/etc to cause the thing to baulk immediately.

* Interfacing with the kernel 
This might require knowing what kernel it is or getting it to run a program (very difficult, particularly if it's already keeled over because of the missing hardware, etc).

* Memory capture issues (corrupt memory images)
Volatility is designed to extract whatever information it can find from the data it's handed.  We often find images that have smear (where the time taken to conduct the image means that a number of pointer/structures have changed and the image as a whole is no longer consistent).

* Malicious images
If you're trusting the OS to give you information, it makes it less useful for malware analysis, since the malware may find a way to return you bad information.  The only way around this would be to not run any code from the image, and that then takes us back to volatility doing the heavy lifting.

* Finding the current DirectoryTableBase (DTB, or page map)
Intel systems at least have a map of memory (this can change from process to process) that is loaded in the CR3 register.  With virtual machine snapshots, this value is stored in the metadata of the snapshot.  Volatility has to find this (and it makes its best guess), and this often requires scanning the entire image and is usually what takes a lot of the time during startup.  If you already know this information you can create a config file to pass to volatility which will greatly speed the automagic process up (you can already use the `--write-config` option to record all the values that were found during the run of a plugin to reuse them with `-c`, thus saving you time when running several plugins against the same memory image).

So, not a ridiculous idea, but unfortunately a couple of things that make it quite tricky to pull off.  If you can find a faster way of locating the DTB, please let us know!  We're always trying to reduce the time taken to locate that value, but security features such as ASLR make that task more difficult (since the same techniques can be used by bad programs to find and reliably change the OS with high enough access).  At the moment we've got two different techniques, one for Windows (which looks for the DTB in the likely range for windows DTBs, and uses a peculiarity of the windows paging mechanism which marks a single entry as pointing to its own table), and the linux/mac method which looks for the kernel banner, and uses the kernel symbol's location for that to find the initial process (which has a DTB that can double for the kernel's DTB).  We also use the difference between where the kernel was found and where the kernel symbols says it should have been to determine the various ASLR values in use on linux.

It might be possible to implement some speed-up specifically for VM images, since they're unlikely to be corrupted if they were from a snapshot, and the metadata would help us immediately fill out some of the information we need (like the DTB), saving us from the slow task of scanning for it.  Since those all depend on outside tools which would come with their own bugs, I'd be very hesitant to add support for them to volatility, but I can well imagine a little tool that either uses the VM snapshot information, or just knows how to read the appropriate metadata for each type of VM, and then produces a volatility config file?  This could speed up working with construction VM images a lot!  I'd be happy to help chat through the concept with you if you'd be interested in coding something up?  Feel free to grab me on [our slack server](https://www.volatilityfoundation.org/slack) if you'd like to keep chatting about this?

For now I'm going to mark this as question so people can see it and then eventually I'll likely close it off, but thank you for the question, it's an interesting idea we hadn't considered too deeply before!  5:)

**Comment by 59e5aaf4** [comment]
Thank you very much for the detailed answer. Indeed, support for third-party metadata parsing is more reasonable. I unfortunately do not have time to invest in this at work, and that's enough computer for me during the day. 
Thanks again for the `-c` protip, I wrongly assumed that was done transparently under the hood by volatility. Should I get some interns some day I'll surely send them towards this doable small scripting task. Bye !
